
/*
============================================================
AUTO-GENERATED FILE: full-schema.sql
Generated at: 2026-04-20 16:02:52.841697Z
Source: All .sql files in schema directory

DO NOT EDIT MANUALLY - EDIT THE SOURCE SQL FILES INSTEAD

Description: This file contains the combined SQL.
Generated by sql-gen.dart script
============================================================
*/

/*
----------------------------------------------------------------------------------------------------------------------------------
- AUTO-GENERATED DROP STATEMENTS FOR SCHEMA OBJECTS
-
- Order matters:
- 1. Tables (depend on types)
- 2. Domains
- 3. Types (ENUMS)
-
- WARNING: Dropping these will cause DATA LOSS. Backup before running.
----------------------------------------------------------------------------------------------------------------------------------

*/
-- TABLES
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.base_destination CASCADE;
DROP TABLE IF EXISTS public.base_destination_reviews CASCADE;
DROP TABLE IF EXISTS public.activities CASCADE;
DROP TABLE IF EXISTS public.travel_packages CASCADE;
DROP TABLE IF EXISTS public.guide_applications CASCADE;
DROP TABLE IF EXISTS public.guide_service_areas_applications CASCADE;
DROP TABLE IF EXISTS public.guides CASCADE;
DROP TABLE IF EXISTS public.guide_service_areas CASCADE;
DROP TABLE IF EXISTS public.suspended_guides CASCADE;
DROP TABLE IF EXISTS public.unsuspension_requests CASCADE;
DROP TABLE IF EXISTS public.guide_reviews CASCADE;
DROP TABLE IF EXISTS public.stories CASCADE;
DROP TABLE IF EXISTS public.story_likes CASCADE;
DROP TABLE IF EXISTS public.story_comments CASCADE;
DROP TABLE IF EXISTS public.photos CASCADE;
DROP TABLE IF EXISTS public.hiring_proposals CASCADE;
DROP TABLE IF EXISTS public.guide_bookings CASCADE;
DROP TABLE IF EXISTS public.package_bookings CASCADE;
DROP TABLE IF EXISTS public.payment_logs CASCADE;
DROP TABLE IF EXISTS public.admin_analytics CASCADE;

-- DOMAINS
DROP DOMAIN IF EXISTS GFM CASCADE;

-- TYPES
DROP TYPE IF EXISTS user_role CASCADE;
DROP TYPE IF EXISTS verification_status CASCADE;
DROP TYPE IF EXISTS booking_status CASCADE;
DROP TYPE IF EXISTS booking_request_status CASCADE;
DROP TYPE IF EXISTS package_type CASCADE;
DROP TYPE IF EXISTS nid_type CASCADE;
DROP TYPE IF EXISTS guide_application_status CASCADE;
DROP TYPE IF EXISTS proposal_status CASCADE;
DROP TYPE IF EXISTS guide_booking_status CASCADE;
DROP TYPE IF EXISTS package_booking_status CASCADE;
DROP TYPE IF EXISTS payment_provider CASCADE;
DROP TYPE IF EXISTS payment_log_status CASCADE;
DROP TYPE IF EXISTS admin_analytics_type CASCADE;

-- VIEWS




-- FILE: schema/extensions.sql
-- EXTENSIONS & ENUMS
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- We will call the markdown text as GFM
CREATE DOMAIN GFM AS TEXT;

-- Enums for strict data integrity
CREATE TYPE user_role AS ENUM ('tourist', 'guide', 'hotel_owner', 'admin');
CREATE TYPE verification_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE booking_status AS ENUM ('pending', 'confirmed', 'completed', 'cancelled', 'reported');
CREATE TYPE booking_request_status AS ENUM ('pending', 'approved', 'rejected', 'confirmed', 'cancelled');


-- FILE: schema/users.sql
-- Profiles: Extends Supabase Auth.users
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,

  first_name text,
  middle_name text,
  last_name text,

  username text UNIQUE,

  phone_number text,
  emergency_contact text,

  avatar_url text,

  -- Onboarding completion and auth verification are derived at runtime
  -- via RPCs using profile-row existence and auth.users confirmation timestamps.
  is_admin boolean DEFAULT false NOT NULL,


  home_location geography(POINT, 4326),
  home_location_name text,


  is_guide boolean DEFAULT false NOT NULL,

  -- true when latest guide application is pending
  is_guide_applicantion_pending boolean DEFAULT false NOT NULL,


  -- We set this field here but never ever use this
  -- this is just to know if the profile created was auto by trigger or not
  is_onboarding_complete boolean DEFAULT false NOT NULL,

  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);


/*
Note: we wont be using the profile table directly,  
Always and always use this function
*/CREATE OR REPLACE FUNCTION public.fetch_profile(target_id uuid DEFAULT auth.uid())
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    auth_user auth.users%ROWTYPE;
    profile_data public.profiles%ROWTYPE;
BEGIN
    -- Get auth user
    SELECT *
    INTO auth_user
    FROM auth.users
    WHERE id = target_id;

    IF auth_user IS NULL THEN
        RETURN jsonb_build_object(
            'profile', NULL,
            'is_onboarding_done', false,
            'is_auth_verified', false
        );
    END IF;

    -- Get profile (may or may not exist)
    SELECT *
    INTO profile_data
    FROM public.profiles
    WHERE id = target_id;

    RETURN jsonb_build_object(

        -- Profile (light)
        'profile',
        CASE 
            WHEN profile_data.id IS NULL THEN NULL
            ELSE to_jsonb(profile_data) - 'is_onboarding_complete'
        END,

        'email', auth_user.email,

        -- Onboarding
        'is_onboarding_done',
        COALESCE(profile_data.is_onboarding_complete, false),

        -- Auth verification (robust)
        'is_auth_verified',
        (
            auth_user.email_confirmed_at IS NOT NULL
            OR auth_user.phone_confirmed_at IS NOT NULL
            OR auth_user.raw_app_meta_data->>'provider' IS NOT NULL
        )
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.is_username_available(p_username text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  normalized text;
BEGIN
  normalized := NULLIF(TRIM(LOWER(p_username)), '');

  IF normalized IS NULL THEN
    RETURN false;
  END IF;

  RETURN NOT EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE LOWER(p.username) = normalized
      AND p.id <> auth.uid()
  );
END;
$$;



-- Verification status is now derived from auth.users inside fetch_profile.




/*
Contract notes:
- guide pending/approval flags are maintained by guide application triggers
- minimal public profile payload across modules must use `public.minimal_user`
- onboarding completion must be done through `complete_onbording`
- auth verification must be derived from `auth.users` confirmation fields
*/

-- FILE: schema/destinations.sql
-- Base destination is the places where we can have travels,
-- these are the most popular places which are loved by tourists or admins
-- Think of it like in google maps, we can see our home only if we set it,  thats the same concept
CREATE TABLE public.base_destination (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,

  coordinates geography(POINT, 4326) NOT NULL,
  radius numeric DEFAULT 25 NOT NULL CHECK (radius > 0), -- Radius in KM
  
  avg_rating numeric CHECK (avg_rating >= 0 AND avg_rating <= 5),
  
  tags text[] DEFAULT '{}',
  
  description GFM,

  feature_image text, -- Single high-quality overview image
  additional_images jsonb NOT NULL DEFAULT '[]', -- other images which can be used in ui but not in featured bg or list thumbnail

  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),

  possible_activities uuid[] DEFAULT '{}', -- Linked to activities table, list of experiences that can be had at this destination, 


  CONSTRAINT min_one_image CHECK (jsonb_array_length(additional_images) >= 1),
  CONSTRAINT max_ten_images CHECK (jsonb_array_length(additional_images) <= 10)
);

CREATE TABLE public.base_destination_reviews (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    destination_id uuid REFERENCES public.base_destination(id) ON DELETE CASCADE,
    tourist_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    rating numeric CHECK (rating >= 0 AND rating <= 5),
    review_text text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- The avg rating should be calculated from reviews via triggers for consistency and actualnes

/*
Activities are just labels for the types of experiences that can be had at a destination. 
They are not tied to specific guides or packages, but rather serve as a way to categorize and filter destinations experience.

*/
CREATE TABLE public.activities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  
  name text NOT NULL UNIQUE,
  description text NOT NULL, -- Just for sake of having it in the db, not  used in the UI at all right now

  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);


/*
Packages are the pre-defined events for travelers to choose from.
They are directly organized by our company, so there is no need to have negotiations or anything
Just book and be ready to go.

Our company has 2 types of packages:
1. destinations_package : A package where the destination is the main focus. The activities and experiences are built around the destination.
2. activities_package : A package where the activities are the main focus. The destination is built around the activities.

Both have same structure, just the difference is the focus, 
what are we focusing,  is it the destination or the activities, 
*/

CREATE TYPE package_type AS ENUM ('destinations_package', 'activities_package');

CREATE TABLE public.travel_packages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  
  type package_type NOT NULL,

  -- Financials
  actual_price numeric NOT NULL CHECK (actual_price >= 0),
  discounted_price numeric NOT NULL CHECK (discounted_price >= 0),

  -- the deadline for the discount price, 
  -- after that the discount price will not be applicable,
  discount_deadline timestamptz,

  -- the expiration date of the package, after that the package will not be bookable,
  expiration_date timestamptz,

  
  featured_image text NOT NULL, -- The main image that will be usedd in lists
  additional_images jsonb NOT NULL DEFAULT '[]', -- other images which can be used in ui but not in featured bg or list thumbnail

  total_days integer NOT NULL CHECK (total_days > 0),

  travel_routes text NOT NULL, -- the textual description of the tour, e.g. "Day 1: Arrival and welcome dinner, Day 2: Trek to base camp, Day 3: Summit attempt, Day 4: Return and relaxation"
  description text, -- Main narrative or description of package, we can think it as,  destination info goes in above but here other like,  rules, what to bring,  how to prepare,  etc.
   
  -- if the routes covers any of the featured destinations then we cann link here, 
  -- this is supposed  to be empty most of the times, so in ui be careful
  destinations_covered uuid[] DEFAULT '{}', -- Linked to base_destination table, list of featured destinations that are covered in this package,  this is for the destination packages,  for activities package it can be empty most of the time,  but we keep it for the sake of flexibility and future proofing

  -- Linked to activities table, the activities that are included in this package,  e.g. trekking,  rafting,  etc.
  -- Even in activities packages it can be of many activities, 
  -- in case of travel package we can call it additional_activities_included. 
  included_activities uuid[] DEFAULT '{}', 

  -- this is for the activities_package,  to know what is the main activity of the package,  e.g. trekking,  rafting,  etc.
  -- Not supposed to be for the destinations_package,
  -- only and only for the activities_package,  
  main_activity uuid REFERENCES public.activities(id) ON DELETE SET NULL,
  
  -- Metadata
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),

  -- Constraints for Quality Control
  CONSTRAINT max_twenty_images CHECK (jsonb_array_length(additional_images) <= 20)
);

-- Keep destination average rating in sync with reviews
CREATE OR REPLACE FUNCTION public.update_base_destination_avg_rating()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_destination_id uuid;
BEGIN
  v_destination_id := COALESCE(NEW.destination_id, OLD.destination_id);

  IF v_destination_id IS NULL THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  UPDATE public.base_destination bd
  SET avg_rating = (
    SELECT ROUND(AVG(r.rating)::numeric, 2)
    FROM public.base_destination_reviews r
    WHERE r.destination_id = v_destination_id
  )
  WHERE bd.id = v_destination_id;

  RETURN COALESCE(NEW, OLD);
END;
$$;



DROP TRIGGER IF EXISTS trg_update_base_destination_avg_rating ON public.base_destination_reviews;
CREATE TRIGGER trg_update_base_destination_avg_rating
AFTER INSERT OR UPDATE OR DELETE ON public.base_destination_reviews
FOR EACH ROW
EXECUTE FUNCTION public.update_base_destination_avg_rating();


-- 4. Indexes for Performant discovery
CREATE INDEX idx_travel_packages_destinations_covered ON public.travel_packages(destinations_covered);
CREATE INDEX idx_travel_packages_type ON public.travel_packages(type);
CREATE INDEX idx_travel_packages_expiration_date ON public.travel_packages(expiration_date);
CREATE INDEX idx_travel_packages_main_activity ON public.travel_packages(main_activity);

-- Indexes
CREATE INDEX idx_base_destination_coordinates ON public.base_destination USING GIST (coordinates);
CREATE INDEX idx_base_destination_reviews_destination_id ON public.base_destination_reviews(destination_id);
CREATE INDEX idx_base_destination_possible_activities ON public.base_destination USING GIN (possible_activities);



/*
We have following modules::
1. Destinations:  
  - THey contains base destinations
  - packages

2. Guides:
  - They are the ones who provide the services to the tourists,  

3. Stories:
  - This is combine of 2 things
  - photos, stories

4. Admin::
  - While technically admin is a role we consider it as a module here
  - THese includes just admin releted works
  - Some actions or things are only for admin e.g guide application approval, suspension etc.

5. Bookings:
  - While you may consider booking as releted to guide or destination but we consider it as a module
  - it contains all the booking releted things,  e.g. booking guide,  booking packages,   etc.
  - this is the only module that should handle the money releted things,  e.g. payment, etc

6. Users:
  - This is the module for the users,  it contains all the user releted things
  - technically it is the base module around which the other modules revolves
  - but this module just contains the user and profile releted things,

7. Applications:
  - THis is the mdule for applications where different applications releted things are handled
  - while technically we can assign these to their respective modules but we decided to make it a seperate module
  - it contains guide application,  unsuspension application,  etc.

But in some entities the module classification is hard, we may get confused on where to place it, 
e.g, guide profile, it is releted to guide but it is also releted to user,  
Dont worry in such case just think and decide in which module it is deeply releted and place it there 
you are never wrong in such case.

*/


-- FILE: schema/guides.sql
CREATE TYPE nid_type AS ENUM ('citizenship', 'nid', 'license', 'pan', 'passport', 'voter_id');
CREATE TYPE guide_application_status AS ENUM ('pending', 'approved', 'rejected');

-- Guide Applications: Verification flow
CREATE TABLE public.guide_applications (
  application_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  nid_document_type nid_type NOT NULL,
  nid_number text NOT NULL,
  nid_photo_url text NOT NULL,
  description GFM,
  previous_experience text,
  known_languages jsonb DEFAULT '[]',
  status guide_application_status DEFAULT 'pending' NOT NULL,
  admin_feedback GFM,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.guide_service_areas_applications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  application_id uuid REFERENCES public.guide_applications(application_id) ON DELETE CASCADE NOT NULL,
  location geography(POINT, 4326) NOT NULL,
  radius_meters numeric NOT NULL CHECK (radius_meters > 0),
  location_name text,
  created_at timestamptz DEFAULT now()
);

-- Guides: Main approved guide table
-- Only the necessary fields are copied her from application
CREATE TABLE public.guides (
  id uuid REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
  description GFM,
  previous_experience text,
  known_languages jsonb DEFAULT '[]',
  admin_feedback GFM,
  
  is_available boolean DEFAULT false NOT NULL,
  is_suspended boolean DEFAULT false NOT NULL,
  avg_rating numeric(2, 1) DEFAULT 0
);

CREATE TABLE public.guide_service_areas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  guide_id uuid REFERENCES public.guides(id) ON DELETE CASCADE NOT NULL,
  location geography(POINT, 4326) NOT NULL,
  radius_meters numeric NOT NULL CHECK (radius_meters > 0),
  location_name text,
  created_at timestamptz DEFAULT now()
);


/*
RLS that only admin can CRUD must be enforced
during read only if the gudide_id matches the auth.uid then return
*/
CREATE TABLE public.suspended_guides (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  guide_id uuid REFERENCES public.guides(id) ON DELETE CASCADE NOT NULL,
  reason GFM,
  admin_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.unsuspension_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  guide_id uuid REFERENCES public.guides(id) ON DELETE CASCADE NOT NULL,
  clarification GFM,
  status guide_application_status DEFAULT 'pending' NOT NULL,
  admin_feedback GFM,
  reviewed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.guide_reviews (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  guide_id uuid REFERENCES public.guides(id) ON DELETE CASCADE NOT NULL,
  reviewer_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  rating numeric(2, 1) CHECK (rating >= 0 AND rating <= 5),
  review_text GFM,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Indexes
CREATE INDEX idx_guide_service_areas_location ON public.guide_service_areas USING GIST (location);
CREATE INDEX idx_guide_application_user_id ON public.guide_applications(user_id);
CREATE INDEX idx_guide_service_areas_applications_location ON public.guide_service_areas_applications USING GIST (location);
CREATE INDEX idx_guide_service_areas_applications_application_id ON public.guide_service_areas_applications(application_id);
CREATE INDEX idx_unsuspension_requests_guide_id ON public.unsuspension_requests(guide_id);
CREATE INDEX idx_guide_reviews_guide_id ON public.guide_reviews(guide_id);



/*
Suspended guides are critical and is not exposed in view
Rather a RPC with check will be used  for suspended guides
the rpc checks if admin is quering or not and return the data accordingly, this is to avoid any accidental exposure of suspended guides in public views
*/
CREATE OR REPLACE FUNCTION public.get_suspended_guides()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
AS $$
DECLARE
  v_is_admin boolean;
BEGIN

SELECT COALESCE(
  (SELECT p.is_admin FROM public.profiles p WHERE p.id = auth.uid()),
  false
) INTO v_is_admin;

IF NOT v_is_admin THEN
  RAISE EXCEPTION 'Unauthorized: admin access required.' USING ERRCODE = '42501';
END IF;

RETURN (
  SELECT COALESCE(jsonb_agg(
  jsonb_build_object(
    'id', sg.guide_id,
    'reason', sg.reason,
    'admin_id', sg.admin_id,
    'created_at', sg.created_at
  ) ORDER BY sg.created_at DESC
), '[]'::jsonb)
  FROM public.suspended_guides sg
);
END;
$$;

-- FILE: schema/stories.sql
-- Stories: User-generated content
CREATE TABLE public.stories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  uploader_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title text NOT NULL,
  feature_image text NOT NULL,
  description GFM NOT NULL,
  categories text,
  tags text[] DEFAULT '{}',
  likes_count integer DEFAULT 0 NOT NULL,
  comments_count integer DEFAULT 0 NOT NULL,
  is_archived boolean DEFAULT false NOT NULL,
  related_location geography(POINT, 4326),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Story Likes
CREATE TABLE public.story_likes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  story_id uuid REFERENCES public.stories(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE(story_id, user_id)
);

-- Story Comments
CREATE TABLE public.story_comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  story_id uuid REFERENCES public.stories(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);



CREATE TABLE public.photos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  uploader_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  media_urls text[] NOT NULL DEFAULT '{}',
  description text,
  location geography(POINT, 4326),
  location_name text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT photos_have_media CHECK (array_length(media_urls, 1) >= 1)
);

CREATE INDEX idx_photos_uploader_id ON public.photos(uploader_id);
CREATE INDEX idx_photos_created_at ON public.photos(created_at DESC);
CREATE INDEX idx_photos_location ON public.photos USING GIST (location);


-- Indexes
CREATE INDEX idx_stories_uploader_id ON public.stories(uploader_id);
CREATE INDEX idx_stories_is_archived ON public.stories(is_archived);
CREATE INDEX idx_stories_related_location ON public.stories USING GIST (related_location);
CREATE INDEX idx_story_likes_story_id ON public.story_likes(story_id);
CREATE INDEX idx_story_comments_story_id ON public.story_comments(story_id);


-- FILE: schema/bookings.sql
CREATE TYPE proposal_status AS ENUM (
  'sent_by_tourist',
  'offered_by_guide',
  'rejected_by_guide',
  'cancelled_by_tourist',
  'accepted_by_tourist'
);

CREATE TYPE guide_booking_status AS ENUM ('confirmed', 'completed', 'cancelled');
CREATE TYPE package_booking_status AS ENUM ('confirmed', 'completed', 'cancelled');
CREATE TYPE payment_provider AS ENUM ('esewa', 'khalti', 'stripe', 'paypal', 'card', 'cash');
CREATE TYPE payment_log_status AS ENUM ('pending', 'succeeded', 'failed', 'refunded');

CREATE TABLE public.hiring_proposals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tourist_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  guide_id uuid NOT NULL REFERENCES public.guides(id) ON DELETE RESTRICT,

  destinations text NOT NULL CHECK (length(trim(destinations)) > 0),
  people_count integer NOT NULL DEFAULT 1 CHECK (people_count > 0),
  duration_days integer NOT NULL CHECK (duration_days > 0),

  -- the tourist gives some extra details about the trip in the proposal,  
  additional_details text,

  total_quoted_price numeric(12, 2) CHECK (total_quoted_price IS NULL OR total_quoted_price >= 0),
  prepay_required numeric(12, 2) CHECK (prepay_required IS NULL OR prepay_required >= 0),
  
  -- these are the remarks the tourist gave on approval
  -- if tourist approves then this is must be set else the tourist_cancellation_remarks must be set
  -- these remarks can be null in pending staus but onnce the proposal is accepted or cancelled by tourist, one of these must be set
  tourist_approval_remarks text,
  tourist_cancellation_remarks text,

  -- simialr to the above guide can also give remarks on rejection why he rejected the tourists proposal,
  -- if he accepts the proposal then it will be stored in the guide_terms field
  -- but if he  rejects then it is stored in the guide_rejection_remarks field, 
  -- and if he hasnt responded yet then both will be null
  guide_cancellation_remarks text,

  -- these are the terms offered by the guide in response to the proposal,  
  -- can be null if guide rejects or hasn't responded yet
  guide_terms text,  
  status proposal_status NOT NULL DEFAULT 'sent_by_tourist',

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT hiring_proposals_price_guard
    CHECK (
      prepay_required IS NULL
      OR total_quoted_price IS NULL
      OR prepay_required <= total_quoted_price
    )
);

CREATE TABLE public.guide_bookings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id uuid UNIQUE NOT NULL REFERENCES public.hiring_proposals(id) ON DELETE RESTRICT,
  tourist_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  guide_id uuid NOT NULL REFERENCES public.guides(id) ON DELETE RESTRICT,

  final_amount numeric(12, 2) NOT NULL CHECK (final_amount >= 0),
  prepay_amount numeric(12, 2) NOT NULL DEFAULT 0 CHECK (prepay_amount >= 0),
  paid_amount numeric(12, 2) NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),

  status guide_booking_status NOT NULL DEFAULT 'confirmed',

  trip_start_date date,
  hired_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT guide_bookings_prepay_lte_final CHECK (prepay_amount <= final_amount),
  CONSTRAINT guide_bookings_paid_lte_final CHECK (paid_amount <= final_amount)
);


CREATE TABLE public.package_bookings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  package_id uuid NOT NULL REFERENCES public.travel_packages(id) ON DELETE RESTRICT,
  tourist_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,

  final_amount numeric(12, 2) NOT NULL CHECK (final_amount >= 0),
  paid_amount numeric(12, 2) NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
  participant_count integer NOT NULL DEFAULT 1 CHECK (participant_count > 0),

  status package_booking_status NOT NULL DEFAULT 'confirmed',

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT package_bookings_paid_lte_final CHECK (paid_amount <= final_amount)
);

CREATE INDEX idx_package_bookings_tourist ON public.package_bookings(tourist_id, created_at DESC);
CREATE INDEX idx_package_bookings_package ON public.package_bookings(package_id, created_at DESC);
CREATE INDEX idx_package_bookings_status ON public.package_bookings(status);

/*
Meant for admin only and not even admin can edit them

They are supposed to come via WEBHooks from the payment providers and we just store them for record and future references
and also to have the payment status updated in our system in case the provider sends us the update

Rls should be like
if the user is admin or either of tourist or guide releted to the log then he can see them but update is impossible
*/
CREATE TABLE public.payment_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  guide_booking_id uuid REFERENCES public.guide_bookings(id) ON DELETE SET NULL,
  package_booking_id uuid REFERENCES public.package_bookings(id) ON DELETE SET NULL,

  tourist_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,

  provider payment_provider NOT NULL,
  provider_txn_id text,
  amount numeric(12, 2) NOT NULL CHECK (amount >= 0),
  currency text NOT NULL DEFAULT 'NPR',
  status payment_log_status NOT NULL DEFAULT 'pending',
  raw_response jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT payment_logs_target_guard CHECK (
    (guide_booking_id IS NOT NULL AND package_booking_id IS NULL)
    OR (guide_booking_id IS NULL AND package_booking_id IS NOT NULL)
  )
);

CREATE INDEX idx_payment_logs_tourist ON public.payment_logs(tourist_id, created_at DESC);
CREATE INDEX idx_payment_logs_guide_booking ON public.payment_logs(guide_booking_id, created_at DESC);
CREATE INDEX idx_payment_logs_package_booking ON public.payment_logs(package_booking_id, created_at DESC);
CREATE INDEX idx_payment_logs_provider_txn_id ON public.payment_logs(provider_txn_id);


 CREATE UNIQUE INDEX idx_hiring_proposals_active_pair
  ON public.hiring_proposals(tourist_id, guide_id)
  WHERE status IN ('sent_by_tourist', 'offered_by_guide');

CREATE INDEX idx_hiring_proposals_tourist ON public.hiring_proposals(tourist_id, created_at DESC);
CREATE INDEX idx_hiring_proposals_guide ON public.hiring_proposals(guide_id, created_at DESC);
CREATE INDEX idx_hiring_proposals_status ON public.hiring_proposals(status);
CREATE INDEX idx_guide_bookings_tourist ON public.guide_bookings(tourist_id, created_at DESC);
CREATE INDEX idx_guide_bookings_guide ON public.guide_bookings(guide_id, created_at DESC);
CREATE INDEX idx_guide_bookings_status ON public.guide_bookings(status);



-- FILE: schema/admin-analytics.sql
CREATE TYPE admin_analytics_type AS ENUM ('daily', 'weekly', 'triday');

CREATE TABLE public.admin_analytics (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  type admin_analytics_type NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT admin_analytics_data_is_object
    CHECK (jsonb_typeof(data) = 'object')
);

CREATE INDEX idx_admin_analytics_type_created_at
  ON public.admin_analytics(type, created_at DESC);

CREATE INDEX idx_admin_analytics_created_at
  ON public.admin_analytics(created_at DESC);


