-- AUTOGENERATED by sql/sql-gen.sh. DO NOT EDIT.

-- ==== sql/rpc/applications.sql ====
-- Applications module RPCs.

create or replace function public.apply_guide_application(
  description text,
  known_languages text[],
  service_areas jsonb,
  previous_experience text default null
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  application_id uuid;
  area jsonb;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  insert into public.guide_applications (
    applicant_id, description, previous_experience, known_languages, status
  )
  values (uid, description, previous_experience, known_languages, 'pending')
  returning id into application_id;

  for area in select * from jsonb_array_elements(service_areas) loop
    insert into public.guide_service_areas_applications (
      application_id, location, radius_meters, location_name
    )
    values (
      application_id,
      st_setsrid(
        st_makepoint(
          (area->'location'->>'longitude')::double precision,
          (area->'location'->>'latitude')::double precision
        ),
        4326
      )::geography,
      (area->>'radius_meters')::double precision,
      area->>'location_name'
    );
  end loop;

  update public.profiles
  set is_guide_applicantion_pending = true, updated_at = now()
  where id = uid;

  return application_id;
end $$;

-- ==== sql/rpc/bookings.sql ====
-- Bookings module RPCs (3-step negotiation flow).

create or replace function public.create_hiring_proposal(
  guide_id uuid,
  destinations uuid[],
  people_count int,
  duration_days int,
  tourist_remarks text default null
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  proposal_id uuid;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  insert into public.hiring_proposals (
    tourist_id, guide_id, destinations, people_count, duration_days, tourist_remarks, status
  )
  values (uid, guide_id, destinations, people_count, duration_days, tourist_remarks, 'sent_by_tourist')
  returning id into proposal_id;
  return proposal_id;
end $$;

create or replace function public.submit_guide_offer(
  proposal_id uuid,
  total_quoted_price numeric,
  prepay_required numeric,
  guide_remarks text default null
)
returns void
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'not authenticated'; end if;
  update public.hiring_proposals
  set total_quoted_price = submit_guide_offer.total_quoted_price,
      prepay_required = submit_guide_offer.prepay_required,
      guide_remarks = submit_guide_offer.guide_remarks,
      status = 'offered_by_guide',
      updated_at = now()
  where id = proposal_id and guide_id = uid and status = 'sent_by_tourist';
  if not found then
    raise exception 'proposal not found or not in expected state';
  end if;
end $$;

create or replace function public.reject_hiring_proposal(
  proposal_id uuid,
  guide_remarks text default null
)
returns void
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'not authenticated'; end if;
  update public.hiring_proposals
  set status = 'rejected_by_guide',
      guide_remarks = reject_hiring_proposal.guide_remarks,
      updated_at = now()
  where id = proposal_id and guide_id = uid and status = 'sent_by_tourist';
end $$;

create or replace function public.cancel_hiring_proposal(proposal_id uuid)
returns void
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'not authenticated'; end if;
  update public.hiring_proposals
  set status = 'cancelled_by_tourist', updated_at = now()
  where id = proposal_id and tourist_id = uid
    and status in ('sent_by_tourist', 'offered_by_guide');
end $$;

create or replace function public.accept_hiring_proposal_and_create_booking(
  proposal_id uuid,
  prepay_amount numeric
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  proposal record;
  booking_id uuid;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  select * into proposal from public.hiring_proposals
  where id = proposal_id and tourist_id = uid and status = 'offered_by_guide'
  for update;
  if not found then
    raise exception 'proposal not available for acceptance';
  end if;
  if prepay_amount < proposal.prepay_required then
    raise exception 'prepay amount below required minimum';
  end if;
  insert into public.guide_bookings (
    proposal_id, tourist_id, guide_id,
    final_amount, prepay_amount, paid_amount, status
  )
  values (
    proposal.id, proposal.tourist_id, proposal.guide_id,
    proposal.total_quoted_price, prepay_amount, 0, 'pending_payment'
  )
  returning id into booking_id;
  update public.hiring_proposals
  set status = 'accepted_by_tourist', updated_at = now()
  where id = proposal.id;
  return booking_id;
end $$;

create or replace function public.create_package_booking(
  package_id uuid,
  people_count int,
  trip_start_date timestamptz
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  pkg record;
  booking_id uuid;
  total numeric;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  select * into pkg from public.travel_packages where id = package_id;
  if not found then raise exception 'package not found'; end if;
  total := coalesce(pkg.discounted_price, pkg.actual_price) * people_count;
  insert into public.package_bookings (
    package_id, tourist_id, people_count, total_amount, paid_amount, trip_start_date, status
  )
  values (package_id, uid, people_count, total, 0, trip_start_date, 'pending_payment')
  returning id into booking_id;
  return booking_id;
end $$;

-- ==== sql/rpc/guides.sql ====
-- Guides module RPCs.

create or replace function public.fetch_guide_profile(target_id uuid default null)
returns jsonb
language sql stable security definer set search_path = public as $$
  select to_jsonb(gi) from public.guide_info gi
  where gi.id = coalesce(target_id, auth.uid())
$$;

create or replace function public.review_guide(
  guide_id uuid,
  rating numeric,
  review_text text default null
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  review_id uuid;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  insert into public.guide_reviews (guide_id, reviewer_id, rating, review_text)
  values (review_guide.guide_id, uid, review_guide.rating, review_guide.review_text)
  returning id into review_id;
  update public.guides g
  set avg_rating = (
    select coalesce(avg(r.rating), 0)
    from public.guide_reviews r
    where r.guide_id = g.id
  )
  where g.id = review_guide.guide_id;
  return review_id;
end $$;

create or replace function public.get_guides_for_destination(
  lat double precision,
  lon double precision,
  result_limit int default 20
)
returns setof public.guide_info
language sql stable security definer set search_path = public as $$
  select gi.*
  from public.guide_info gi
  join public.guide_service_areas sa on sa.guide_id = gi.id
  where st_dwithin(
    sa.location,
    st_setsrid(st_makepoint(lon, lat), 4326)::geography,
    sa.radius_meters
  )
  and (gi->>'is_available')::boolean = true
  and (gi->>'is_suspended')::boolean = false
  order by gi.avg_rating desc
  limit result_limit
$$;

create or replace function public.get_suspended_guides()
returns jsonb
language sql stable security definer set search_path = public as $$
  select coalesce(jsonb_agg(to_jsonb(sg) order by sg.suspended_at desc), '[]'::jsonb)
  from public.suspended_guides sg
  where sg.lifted_at is null
$$;

-- ==== sql/rpc/users.sql ====
-- Users module RPCs.

create or replace function public.fetch_profile(target_id uuid default null)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  resolved_id uuid := coalesce(target_id, auth.uid());
  result jsonb;
begin
  if resolved_id is null then
    raise exception 'not authenticated';
  end if;
  select to_jsonb(p) into result from public.profiles p where p.id = resolved_id;
  if result is null then
    raise exception 'profile not found';
  end if;
  -- Redact home_location into lat/lon jsonb for the client.
  if result ? 'home_location' then
    result := jsonb_set(
      result,
      '{home_location}',
      case
        when (select home_location is null from public.profiles where id = resolved_id) then 'null'::jsonb
        else (
          select jsonb_build_object(
            'latitude', st_y(home_location::geometry),
            'longitude', st_x(home_location::geometry)
          )
          from public.profiles where id = resolved_id
        )
      end
    );
  end if;
  return result;
end $$;

create or replace function public.is_username_available(username text)
returns boolean
language sql stable security definer set search_path = public as $$
  select not exists (select 1 from public.profiles p where p.username = is_username_available.username);
$$;

create or replace function public.complete_onbording(
  first_name text,
  last_name text,
  username text,
  middle_name text default null,
  phone_number text default null,
  emergency_contact text default null,
  avatar_url text default null,
  home_location jsonb default null,
  home_location_name text default null
)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  home geography;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  if home_location is not null then
    home := st_setsrid(
      st_makepoint(
        (home_location->>'longitude')::double precision,
        (home_location->>'latitude')::double precision
      ),
      4326
    )::geography;
  end if;
  insert into public.profiles (
    id, first_name, middle_name, last_name, username,
    phone_number, emergency_contact, avatar_url,
    home_location, home_location_name, is_onboarding_complete
  )
  values (
    uid, first_name, middle_name, last_name, username,
    phone_number, emergency_contact, avatar_url,
    home, home_location_name, true
  )
  on conflict (id) do update set
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    username = excluded.username,
    phone_number = excluded.phone_number,
    emergency_contact = excluded.emergency_contact,
    avatar_url = excluded.avatar_url,
    home_location = excluded.home_location,
    home_location_name = excluded.home_location_name,
    is_onboarding_complete = true,
    updated_at = now();
  return public.fetch_profile(uid);
end $$;

-- ==== sql/admin/rpc/admin_analytics.sql ====
-- Admin analytics RPCs.

create or replace function public.build_admin_analytics_payload(days int default 30)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare result jsonb;
begin
  perform public._assert_admin();
  select jsonb_build_object(
    'id', uuid_generate_v4(),
    'type', 'system_overview',
    'payload', jsonb_build_object(
      'window_days', days,
      'total_users', (select count(*) from public.profiles),
      'new_users', (
        select count(*) from public.profiles
        where created_at > now() - (days || ' days')::interval
      ),
      'new_bookings', (
        select count(*) from public.guide_bookings
        where hired_at > now() - (days || ' days')::interval
      ),
      'payment_volume', (
        select coalesce(sum(amount), 0) from public.payment_logs
        where status = 'succeeded'
          and created_at > now() - (days || ' days')::interval
      )
    ),
    'captured_at', now()
  ) into result;
  return result;
end $$;

create or replace function public.capture_admin_analytics_snapshot(
  type text,
  days int default 30
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  new_id uuid;
  payload jsonb;
begin
  perform public._assert_admin();
  payload := public.build_admin_analytics_payload(days);
  insert into public.admin_analytics (type, payload)
  values (type, payload)
  returning id into new_id;
  return new_id;
end $$;

create or replace function public.capture_all_admin_analytics_snapshots()
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  types text[] := array['system_overview'];
  t text;
  ids uuid[] := '{}';
begin
  perform public._assert_admin();
  foreach t in array types loop
    ids := ids || public.capture_admin_analytics_snapshot(t);
  end loop;
  return jsonb_build_object('captured_ids', to_jsonb(ids));
end $$;

create or replace function public.run_admin_analytics_midnight_job()
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public.capture_all_admin_analytics_snapshots();
end $$;

create or replace function public.schedule_admin_analytics_midnight_job()
returns text
language plpgsql security definer set search_path = public as $$
begin
  perform cron.schedule(
    'admin_analytics_midnight',
    '0 0 * * *',
    $job$ select public.run_admin_analytics_midnight_job(); $job$
  );
  return 'admin_analytics_midnight';
end $$;

-- ==== sql/admin/rpc/admin_crud.sql ====
-- Admin CRUD RPCs. All require is_admin = true on caller's profile.

create or replace function public._assert_admin()
returns void
language plpgsql security definer set search_path = public as $$
declare is_admin boolean;
begin
  select p.is_admin into is_admin from public.profiles p where p.id = auth.uid();
  if not coalesce(is_admin, false) then
    raise exception 'admin required';
  end if;
end $$;

create or replace function public.admin_create_base_destination(
  name text,
  coordinates jsonb,
  radius double precision,
  description text default '',
  tags text[] default '{}',
  feature_image text default null,
  additional_images text[] default '{}',
  possible_activities uuid[] default '{}'
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare new_id uuid;
begin
  perform public._assert_admin();
  insert into public.base_destination (
    name, coordinates, radius, description, tags,
    feature_image, additional_images, possible_activities
  )
  values (
    name,
    st_setsrid(
      st_makepoint(
        (coordinates->>'longitude')::double precision,
        (coordinates->>'latitude')::double precision
      ),
      4326
    )::geography,
    radius, description, tags, feature_image, additional_images, possible_activities
  )
  returning id into new_id;
  return new_id;
end $$;

create or replace function public.admin_update_base_destination(
  target_id uuid,
  name text default null,
  coordinates jsonb default null,
  radius double precision default null,
  description text default null,
  tags text[] default null,
  feature_image text default null,
  additional_images text[] default null,
  possible_activities uuid[] default null
)
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public._assert_admin();
  update public.base_destination
  set
    name = coalesce(admin_update_base_destination.name, name),
    coordinates = case
      when admin_update_base_destination.coordinates is null then coordinates
      else st_setsrid(
        st_makepoint(
          (admin_update_base_destination.coordinates->>'longitude')::double precision,
          (admin_update_base_destination.coordinates->>'latitude')::double precision
        ),
        4326
      )::geography
    end,
    radius = coalesce(admin_update_base_destination.radius, radius),
    description = coalesce(admin_update_base_destination.description, description),
    tags = coalesce(admin_update_base_destination.tags, tags),
    feature_image = coalesce(admin_update_base_destination.feature_image, feature_image),
    additional_images = coalesce(admin_update_base_destination.additional_images, additional_images),
    possible_activities = coalesce(admin_update_base_destination.possible_activities, possible_activities),
    updated_at = now()
  where id = target_id;
end $$;

create or replace function public.admin_delete_base_destination(target_id uuid)
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public._assert_admin();
  delete from public.base_destination where id = target_id;
end $$;

create or replace function public.admin_create_activity(
  name text,
  icon text default null,
  description text default null,
  feature_image text default null
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare new_id uuid;
begin
  perform public._assert_admin();
  insert into public.activities (name, icon, description, feature_image)
  values (name, icon, description, feature_image)
  returning id into new_id;
  return new_id;
end $$;

create or replace function public.admin_update_activity(
  target_id uuid,
  name text default null,
  icon text default null,
  description text default null,
  feature_image text default null
)
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public._assert_admin();
  update public.activities
  set
    name = coalesce(admin_update_activity.name, name),
    icon = coalesce(admin_update_activity.icon, icon),
    description = coalesce(admin_update_activity.description, description),
    feature_image = coalesce(admin_update_activity.feature_image, feature_image)
  where id = target_id;
end $$;

create or replace function public.admin_delete_activity(target_id uuid)
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public._assert_admin();
  delete from public.activities where id = target_id;
end $$;

create or replace function public.admin_create_travel_package(
  name text,
  type travel_package_type,
  actual_price numeric,
  total_days int,
  description text default '',
  discounted_price numeric default null,
  discount_deadline timestamptz default null,
  expiration_date timestamptz default null,
  featured_image text default null,
  additional_images text[] default '{}',
  travel_routes text[] default '{}',
  destinations_covered uuid[] default '{}',
  included_activities uuid[] default '{}',
  main_activity uuid default null
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare new_id uuid;
begin
  perform public._assert_admin();
  insert into public.travel_packages (
    name, type, actual_price, discounted_price, discount_deadline, expiration_date,
    featured_image, additional_images, total_days, travel_routes,
    description, destinations_covered, included_activities, main_activity
  )
  values (
    name, type, actual_price, discounted_price, discount_deadline, expiration_date,
    featured_image, additional_images, total_days, travel_routes,
    description, destinations_covered, included_activities, main_activity
  )
  returning id into new_id;
  return new_id;
end $$;

create or replace function public.admin_update_travel_package(
  target_id uuid,
  name text default null,
  type travel_package_type default null,
  actual_price numeric default null,
  discounted_price numeric default null,
  discount_deadline timestamptz default null,
  expiration_date timestamptz default null,
  featured_image text default null,
  additional_images text[] default null,
  total_days int default null,
  travel_routes text[] default null,
  description text default null,
  destinations_covered uuid[] default null,
  included_activities uuid[] default null,
  main_activity uuid default null
)
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public._assert_admin();
  update public.travel_packages
  set
    name = coalesce(admin_update_travel_package.name, name),
    type = coalesce(admin_update_travel_package.type, type),
    actual_price = coalesce(admin_update_travel_package.actual_price, actual_price),
    discounted_price = coalesce(admin_update_travel_package.discounted_price, discounted_price),
    discount_deadline = coalesce(admin_update_travel_package.discount_deadline, discount_deadline),
    expiration_date = coalesce(admin_update_travel_package.expiration_date, expiration_date),
    featured_image = coalesce(admin_update_travel_package.featured_image, featured_image),
    additional_images = coalesce(admin_update_travel_package.additional_images, additional_images),
    total_days = coalesce(admin_update_travel_package.total_days, total_days),
    travel_routes = coalesce(admin_update_travel_package.travel_routes, travel_routes),
    description = coalesce(admin_update_travel_package.description, description),
    destinations_covered = coalesce(admin_update_travel_package.destinations_covered, destinations_covered),
    included_activities = coalesce(admin_update_travel_package.included_activities, included_activities),
    main_activity = coalesce(admin_update_travel_package.main_activity, main_activity),
    updated_at = now()
  where id = target_id;
end $$;

create or replace function public.admin_delete_travel_package(target_id uuid)
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public._assert_admin();
  delete from public.travel_packages where id = target_id;
end $$;

create or replace function public.change_guide_application_status(
  application_id uuid,
  new_status guide_application_status,
  feedback text default null
)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  app record;
begin
  perform public._assert_admin();
  update public.guide_applications
  set status = new_status,
      admin_feedback = feedback,
      updated_at = now()
  where id = application_id
  returning * into app;

  if new_status = 'approved' then
    insert into public.guides (id, description, previous_experience, known_languages)
    values (app.applicant_id, app.description, app.previous_experience, app.known_languages)
    on conflict (id) do update
      set description = excluded.description,
          previous_experience = excluded.previous_experience,
          known_languages = excluded.known_languages,
          is_suspended = false,
          updated_at = now();
    update public.profiles
    set is_guide = true, is_guide_applicantion_pending = false, updated_at = now()
    where id = app.applicant_id;
  elsif new_status in ('rejected', 'revision_requested') then
    update public.profiles
    set is_guide_applicantion_pending = (new_status = 'revision_requested'),
        updated_at = now()
    where id = app.applicant_id;
  end if;

  return to_jsonb(app);
end $$;

create or replace function public.change_guide_suspend_status(
  guide_id uuid,
  suspend boolean,
  reason text default null
)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare suspension_id uuid;
begin
  perform public._assert_admin();
  update public.guides set is_suspended = suspend, updated_at = now() where id = guide_id;
  if suspend then
    insert into public.suspended_guides (guide_id, reason, suspended_by)
    values (guide_id, coalesce(reason, ''), auth.uid())
    returning id into suspension_id;
  else
    update public.suspended_guides
    set lifted_at = now()
    where guide_id = change_guide_suspend_status.guide_id and lifted_at is null;
  end if;
  return jsonb_build_object('guide_id', guide_id, 'suspended', suspend);
end $$;

