-- AUTOGENERATED by sql/sql-gen.sh. DO NOT EDIT.

-- SCHEMA
-- AUTOGENERATED by sql/sql-gen.sh. DO NOT EDIT.

-- ==== sql/schema/00_extensions.sql ====
-- Required Postgres extensions.

create extension if not exists "uuid-ossp";
create extension if not exists postgis;
create extension if not exists pg_cron;

-- ==== sql/schema/01_enums.sql ====
-- Platform-wide enums. Keep in sync with backend/v2/schemas/enums.ts.

do $$ begin
  create type hiring_proposal_status as enum (
    'sent_by_tourist',
    'offered_by_guide',
    'rejected_by_guide',
    'cancelled_by_tourist',
    'accepted_by_tourist'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type booking_status as enum (
    'pending_payment',
    'confirmed',
    'in_progress',
    'completed',
    'cancelled',
    'disputed'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type payment_status as enum (
    'pending',
    'succeeded',
    'failed',
    'refunded'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type guide_application_status as enum (
    'pending',
    'approved',
    'rejected',
    'revision_requested'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type unsuspension_request_status as enum (
    'pending',
    'approved',
    'rejected'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type travel_package_type as enum ('destination', 'activity');
exception when duplicate_object then null; end $$;

do $$ begin
  create type story_visibility as enum ('public', 'unlisted', 'archived');
exception when duplicate_object then null; end $$;

-- ==== sql/schema/10_profiles.sql ====
-- Users module.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  middle_name text,
  last_name text,
  username text not null unique,
  phone_number text,
  emergency_contact text,
  avatar_url text,
  is_admin boolean not null default false,
  is_guide boolean not null default false,
  is_guide_applicantion_pending boolean not null default false,
  is_onboarding_complete boolean not null default false,
  home_location geography(point, 4326),
  home_location_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_username_idx on public.profiles (username);
create index if not exists profiles_home_location_idx
  on public.profiles using gist (home_location);

-- ==== sql/schema/20_destinations.sql ====
-- Destinations module.

create table if not exists public.base_destination (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  coordinates geography(point, 4326) not null,
  radius double precision not null check (radius > 0),
  avg_rating numeric(3, 2) not null default 0,
  tags text[] not null default '{}',
  description text not null default '',
  feature_image text,
  additional_images text[] not null default '{}',
  possible_activities uuid[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists base_destination_coords_idx
  on public.base_destination using gist (coordinates);

create table if not exists public.base_destination_reviews (
  id uuid primary key default uuid_generate_v4(),
  destination_id uuid not null references public.base_destination(id) on delete cascade,
  reviewer_id uuid not null references public.profiles(id) on delete cascade,
  rating numeric(3, 2) not null check (rating between 0 and 5),
  review_text text,
  created_at timestamptz not null default now()
);

create table if not exists public.activities (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  icon text,
  description text,
  feature_image text,
  created_at timestamptz not null default now()
);

create table if not exists public.travel_packages (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  type travel_package_type not null,
  actual_price numeric(12, 2) not null check (actual_price >= 0),
  discounted_price numeric(12, 2),
  discount_deadline timestamptz,
  expiration_date timestamptz,
  featured_image text,
  additional_images text[] not null default '{}',
  total_days int not null check (total_days > 0),
  travel_routes text[] not null default '{}',
  description text not null default '',
  destinations_covered uuid[] not null default '{}',
  included_activities uuid[] not null default '{}',
  main_activity uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ==== sql/schema/30_guides.sql ====
-- Guides module.

create table if not exists public.guides (
  id uuid primary key references public.profiles(id) on delete cascade,
  description text not null default '',
  previous_experience text,
  known_languages text[] not null default '{}',
  admin_feedback text,
  is_available boolean not null default true,
  is_suspended boolean not null default false,
  avg_rating numeric(3, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guide_service_areas (
  id uuid primary key default uuid_generate_v4(),
  guide_id uuid not null references public.guides(id) on delete cascade,
  location geography(point, 4326) not null,
  radius_meters double precision not null check (radius_meters > 0),
  location_name text not null
);
create index if not exists guide_service_areas_loc_idx
  on public.guide_service_areas using gist (location);

create table if not exists public.guide_reviews (
  id uuid primary key default uuid_generate_v4(),
  guide_id uuid not null references public.guides(id) on delete cascade,
  reviewer_id uuid not null references public.profiles(id) on delete cascade,
  rating numeric(3, 2) not null check (rating between 0 and 5),
  review_text text,
  created_at timestamptz not null default now()
);

create table if not exists public.suspended_guides (
  id uuid primary key default uuid_generate_v4(),
  guide_id uuid not null references public.guides(id) on delete cascade,
  reason text not null,
  suspended_at timestamptz not null default now(),
  suspended_by uuid not null references public.profiles(id),
  lifted_at timestamptz
);

-- ==== sql/schema/40_stories.sql ====
-- Stories & photos module.

create table if not exists public.stories (
  id uuid primary key default uuid_generate_v4(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  content text not null default '',
  feature_image text,
  tags text[] not null default '{}',
  categories text[] not null default '{}',
  location geography(point, 4326),
  location_name text,
  visibility story_visibility not null default 'public',
  like_count int not null default 0,
  comment_count int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.story_likes (
  story_id uuid not null references public.stories(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (story_id, user_id)
);

create table if not exists public.story_comments (
  id uuid primary key default uuid_generate_v4(),
  story_id uuid not null references public.stories(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.photos (
  id uuid primary key default uuid_generate_v4(),
  uploader_id uuid not null references public.profiles(id) on delete cascade,
  image_url text not null,
  description text,
  location geography(point, 4326),
  location_name text,
  created_at timestamptz not null default now()
);

-- ==== sql/schema/50_bookings.sql ====
-- Bookings module.

create table if not exists public.hiring_proposals (
  id uuid primary key default uuid_generate_v4(),
  tourist_id uuid not null references public.profiles(id) on delete cascade,
  guide_id uuid not null references public.guides(id) on delete cascade,
  destinations uuid[] not null default '{}',
  people_count int not null check (people_count > 0),
  duration_days int not null check (duration_days > 0),
  total_quoted_price numeric(12, 2),
  prepay_required numeric(12, 2),
  status hiring_proposal_status not null default 'sent_by_tourist',
  tourist_remarks text,
  guide_remarks text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guide_bookings (
  id uuid primary key default uuid_generate_v4(),
  proposal_id uuid not null references public.hiring_proposals(id) on delete cascade,
  tourist_id uuid not null references public.profiles(id) on delete cascade,
  guide_id uuid not null references public.guides(id) on delete cascade,
  final_amount numeric(12, 2) not null,
  prepay_amount numeric(12, 2) not null,
  paid_amount numeric(12, 2) not null default 0,
  status booking_status not null default 'pending_payment',
  trip_start_date timestamptz,
  hired_at timestamptz not null default now()
);

create table if not exists public.package_bookings (
  id uuid primary key default uuid_generate_v4(),
  package_id uuid not null references public.travel_packages(id) on delete cascade,
  tourist_id uuid not null references public.profiles(id) on delete cascade,
  people_count int not null check (people_count > 0),
  total_amount numeric(12, 2) not null,
  paid_amount numeric(12, 2) not null default 0,
  status booking_status not null default 'pending_payment',
  trip_start_date timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.payment_logs (
  id uuid primary key default uuid_generate_v4(),
  guide_booking_id uuid references public.guide_bookings(id) on delete set null,
  package_booking_id uuid references public.package_bookings(id) on delete set null,
  tourist_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null,
  provider_txn_id text not null,
  amount numeric(12, 2) not null,
  currency text not null default 'NPR',
  status payment_status not null default 'pending',
  raw_response jsonb,
  created_at timestamptz not null default now(),
  check (guide_booking_id is not null or package_booking_id is not null)
);

-- ==== sql/schema/60_applications.sql ====
-- Applications module.

create table if not exists public.guide_applications (
  id uuid primary key default uuid_generate_v4(),
  applicant_id uuid not null references public.profiles(id) on delete cascade,
  description text not null default '',
  previous_experience text,
  known_languages text[] not null default '{}',
  status guide_application_status not null default 'pending',
  admin_feedback text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guide_service_areas_applications (
  id uuid primary key default uuid_generate_v4(),
  application_id uuid not null references public.guide_applications(id) on delete cascade,
  location geography(point, 4326) not null,
  radius_meters double precision not null check (radius_meters > 0),
  location_name text not null
);

create table if not exists public.unsuspension_requests (
  id uuid primary key default uuid_generate_v4(),
  guide_id uuid not null references public.guides(id) on delete cascade,
  reason text not null,
  status unsuspension_request_status not null default 'pending',
  admin_feedback text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ==== sql/admin/schema/00_admin_tables.sql ====
-- Admin-only tables (isolated from main schema for clarity).

create table if not exists public.admin_analytics (
  id uuid primary key default uuid_generate_v4(),
  type text not null,
  payload jsonb not null,
  captured_at timestamptz not null default now()
);

create index if not exists admin_analytics_type_idx
  on public.admin_analytics (type, captured_at desc);

-- VIEWS
-- AUTOGENERATED by sql/sql-gen.sh. DO NOT EDIT.

-- ==== sql/views/bookings.sql ====
-- Bookings module read views.

create or replace view public.guide_booking_requests as
  select
    hp.*
  from public.hiring_proposals hp;

create or replace view public.guide_bookings_info as
  select
    gb.*,
    coalesce(
      (
        select jsonb_agg(to_jsonb(pl) order by pl.created_at)
        from public.payment_logs pl
        where pl.guide_booking_id = gb.id
      ),
      '[]'::jsonb
    ) as payments
  from public.guide_bookings gb;

create or replace view public.package_bookings_info as
  select
    pb.*,
    coalesce(
      (
        select jsonb_agg(to_jsonb(pl) order by pl.created_at)
        from public.payment_logs pl
        where pl.package_booking_id = pb.id
      ),
      '[]'::jsonb
    ) as payments
  from public.package_bookings pb;

-- ==== sql/views/destinations.sql ====
-- Destinations module read views.

create or replace view public.destinations as
  select
    d.id,
    d.name,
    jsonb_build_object(
      'latitude', st_y(d.coordinates::geometry),
      'longitude', st_x(d.coordinates::geometry)
    ) as coordinates,
    d.radius,
    d.avg_rating,
    d.tags,
    d.description,
    d.feature_image,
    d.additional_images,
    d.possible_activities,
    d.created_at,
    d.updated_at,
    coalesce(
      (
        select jsonb_agg(jsonb_build_object('id', a.id, 'name', a.name, 'icon', a.icon))
        from public.activities a
        where a.id = any(d.possible_activities)
      ),
      '[]'::jsonb
    ) as activities
  from public.base_destination d;

create or replace view public.destination_reviews as
  select
    r.id,
    r.destination_id,
    r.reviewer_id,
    r.rating,
    r.review_text,
    r.created_at,
    p.username as reviewer_username,
    p.avatar_url as reviewer_avatar_url
  from public.base_destination_reviews r
  left join public.profiles p on p.id = r.reviewer_id;

create or replace view public.available_activities as
  select * from public.activities order by name asc;

create or replace view public.destination_packages as
  select * from public.travel_packages
  where type = 'destination'
    and (expiration_date is null or expiration_date > now());

create or replace view public.activities_packages as
  select * from public.travel_packages
  where type = 'activity'
    and (expiration_date is null or expiration_date > now());

-- ==== sql/views/guides.sql ====
-- Guides module read views.

create or replace view public.guide_info as
  select
    g.id,
    g.description,
    g.previous_experience,
    g.known_languages,
    g.admin_feedback,
    g.is_available,
    g.is_suspended,
    g.avg_rating,
    g.created_at,
    g.updated_at,
    jsonb_build_object(
      'id', p.id,
      'username', p.username,
      'first_name', p.first_name,
      'last_name', p.last_name,
      'avatar_url', p.avatar_url
    ) as user,
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', sa.id,
            'guide_id', sa.guide_id,
            'location', jsonb_build_object(
              'latitude', st_y(sa.location::geometry),
              'longitude', st_x(sa.location::geometry)
            ),
            'radius_meters', sa.radius_meters,
            'location_name', sa.location_name
          )
        )
        from public.guide_service_areas sa
        where sa.guide_id = g.id
      ),
      '[]'::jsonb
    ) as service_areas
  from public.guides g
  join public.profiles p on p.id = g.id;

create or replace view public.available_guides as
  select * from public.guide_info
  where is_available = true and is_suspended = false;

-- ==== sql/views/stories.sql ====
-- Stories & photos module read views.

create or replace view public.stories_info as
  select
    s.id,
    s.author_id,
    s.title,
    s.content,
    s.feature_image,
    s.tags,
    s.categories,
    case
      when s.location is null then null
      else jsonb_build_object(
        'latitude', st_y(s.location::geometry),
        'longitude', st_x(s.location::geometry)
      )
    end as location,
    s.location_name,
    s.visibility,
    s.like_count,
    s.comment_count,
    s.created_at,
    s.updated_at,
    jsonb_build_object(
      'id', p.id,
      'username', p.username,
      'first_name', p.first_name,
      'last_name', p.last_name,
      'avatar_url', p.avatar_url
    ) as author
  from public.stories s
  left join public.profiles p on p.id = s.author_id;

create or replace view public.photos_info as
  select
    ph.id,
    ph.uploader_id,
    ph.image_url,
    ph.description,
    case
      when ph.location is null then null
      else jsonb_build_object(
        'latitude', st_y(ph.location::geometry),
        'longitude', st_x(ph.location::geometry)
      )
    end as location,
    ph.location_name,
    ph.created_at,
    jsonb_build_object(
      'id', p.id,
      'username', p.username,
      'first_name', p.first_name,
      'last_name', p.last_name,
      'avatar_url', p.avatar_url
    ) as uploader
  from public.photos ph
  left join public.profiles p on p.id = ph.uploader_id;

-- ==== sql/views/users.sql ====
-- Users module read views.

create or replace view public.user_info as
  select
    p.id,
    p.username,
    p.first_name,
    p.middle_name,
    p.last_name,
    p.avatar_url,
    p.is_admin,
    p.is_guide,
    p.is_onboarding_complete,
    p.home_location_name,
    p.created_at
  from public.profiles p;

create or replace view public.minimal_user as
  select
    p.id,
    p.username,
    p.first_name,
    p.last_name,
    p.avatar_url
  from public.profiles p;

-- ==== sql/admin/views/admin.sql ====
-- Admin-only read views. Always filter behind RLS to admins.

create or replace view public.admin_pending_guide_applications as
  select
    ga.*,
    jsonb_build_object(
      'id', p.id,
      'username', p.username,
      'first_name', p.first_name,
      'last_name', p.last_name
    ) as applicant
  from public.guide_applications ga
  left join public.profiles p on p.id = ga.applicant_id
  where ga.status = 'pending'
  order by ga.created_at asc;

create or replace view public.admin_pending_unsuspension_requests as
  select
    ur.*,
    jsonb_build_object(
      'id', p.id,
      'username', p.username,
      'first_name', p.first_name,
      'last_name', p.last_name
    ) as guide
  from public.unsuspension_requests ur
  left join public.profiles p on p.id = ur.guide_id
  where ur.status = 'pending'
  order by ur.created_at asc;

create or replace view public.admin_booking_negotiation_queue as
  select * from public.hiring_proposals
  where status in ('sent_by_tourist', 'offered_by_guide')
  order by updated_at desc;

create or replace view public.admin_payment_review_queue as
  select * from public.payment_logs
  where status = 'pending'
  order by created_at asc;

create or replace view public.admin_package_health_queue as
  select * from public.travel_packages
  where expiration_date is not null
    and expiration_date > now()
    and expiration_date < now() + interval '7 days'
  order by expiration_date asc;

create or replace view public.admin_package_booking_requests as
  select pb.*,
         tp.name as package_name
  from public.package_bookings pb
  join public.travel_packages tp on tp.id = pb.package_id
  where pb.status = 'pending_payment'
  order by pb.created_at desc;

create or replace view public.admin_system_overview as
  select
    (select count(*) from public.profiles) as total_users,
    (select count(*) from public.guides where is_suspended = false) as total_guides,
    (select count(*) from public.guide_applications where status = 'pending') as pending_guide_applications,
    (select count(*) from public.guide_bookings
      where status in ('pending_payment', 'confirmed', 'in_progress')) as active_bookings,
    (select count(*) from public.payment_logs where status = 'pending') as pending_payment_reviews,
    (select count(*) from public.guides where is_suspended = true) as suspended_guides;

-- RPC
-- AUTOGENERATED by sql/sql-gen.sh. DO NOT EDIT.

-- ==== sql/rpc/applications.sql ====
-- Applications module RPCs.

create or replace function public.apply_guide_application(
  description text,
  known_languages text[],
  service_areas jsonb,
  previous_experience text default null
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  application_id uuid;
  area jsonb;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  insert into public.guide_applications (
    applicant_id, description, previous_experience, known_languages, status
  )
  values (uid, description, previous_experience, known_languages, 'pending')
  returning id into application_id;

  for area in select * from jsonb_array_elements(service_areas) loop
    insert into public.guide_service_areas_applications (
      application_id, location, radius_meters, location_name
    )
    values (
      application_id,
      st_setsrid(
        st_makepoint(
          (area->'location'->>'longitude')::double precision,
          (area->'location'->>'latitude')::double precision
        ),
        4326
      )::geography,
      (area->>'radius_meters')::double precision,
      area->>'location_name'
    );
  end loop;

  update public.profiles
  set is_guide_applicantion_pending = true, updated_at = now()
  where id = uid;

  return application_id;
end $$;

-- ==== sql/rpc/bookings.sql ====
-- Bookings module RPCs (3-step negotiation flow).

create or replace function public.create_hiring_proposal(
  guide_id uuid,
  destinations uuid[],
  people_count int,
  duration_days int,
  tourist_remarks text default null
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  proposal_id uuid;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  insert into public.hiring_proposals (
    tourist_id, guide_id, destinations, people_count, duration_days, tourist_remarks, status
  )
  values (uid, guide_id, destinations, people_count, duration_days, tourist_remarks, 'sent_by_tourist')
  returning id into proposal_id;
  return proposal_id;
end $$;

create or replace function public.submit_guide_offer(
  proposal_id uuid,
  total_quoted_price numeric,
  prepay_required numeric,
  guide_remarks text default null
)
returns void
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'not authenticated'; end if;
  update public.hiring_proposals
  set total_quoted_price = submit_guide_offer.total_quoted_price,
      prepay_required = submit_guide_offer.prepay_required,
      guide_remarks = submit_guide_offer.guide_remarks,
      status = 'offered_by_guide',
      updated_at = now()
  where id = proposal_id and guide_id = uid and status = 'sent_by_tourist';
  if not found then
    raise exception 'proposal not found or not in expected state';
  end if;
end $$;

create or replace function public.reject_hiring_proposal(
  proposal_id uuid,
  guide_remarks text default null
)
returns void
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'not authenticated'; end if;
  update public.hiring_proposals
  set status = 'rejected_by_guide',
      guide_remarks = reject_hiring_proposal.guide_remarks,
      updated_at = now()
  where id = proposal_id and guide_id = uid and status = 'sent_by_tourist';
end $$;

create or replace function public.cancel_hiring_proposal(proposal_id uuid)
returns void
language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'not authenticated'; end if;
  update public.hiring_proposals
  set status = 'cancelled_by_tourist', updated_at = now()
  where id = proposal_id and tourist_id = uid
    and status in ('sent_by_tourist', 'offered_by_guide');
end $$;

create or replace function public.accept_hiring_proposal_and_create_booking(
  proposal_id uuid,
  prepay_amount numeric
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  proposal record;
  booking_id uuid;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  select * into proposal from public.hiring_proposals
  where id = proposal_id and tourist_id = uid and status = 'offered_by_guide'
  for update;
  if not found then
    raise exception 'proposal not available for acceptance';
  end if;
  if prepay_amount < proposal.prepay_required then
    raise exception 'prepay amount below required minimum';
  end if;
  insert into public.guide_bookings (
    proposal_id, tourist_id, guide_id,
    final_amount, prepay_amount, paid_amount, status
  )
  values (
    proposal.id, proposal.tourist_id, proposal.guide_id,
    proposal.total_quoted_price, prepay_amount, 0, 'pending_payment'
  )
  returning id into booking_id;
  update public.hiring_proposals
  set status = 'accepted_by_tourist', updated_at = now()
  where id = proposal.id;
  return booking_id;
end $$;

create or replace function public.create_package_booking(
  package_id uuid,
  people_count int,
  trip_start_date timestamptz
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  pkg record;
  booking_id uuid;
  total numeric;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  select * into pkg from public.travel_packages where id = package_id;
  if not found then raise exception 'package not found'; end if;
  total := coalesce(pkg.discounted_price, pkg.actual_price) * people_count;
  insert into public.package_bookings (
    package_id, tourist_id, people_count, total_amount, paid_amount, trip_start_date, status
  )
  values (package_id, uid, people_count, total, 0, trip_start_date, 'pending_payment')
  returning id into booking_id;
  return booking_id;
end $$;

-- ==== sql/rpc/guides.sql ====
-- Guides module RPCs.

create or replace function public.fetch_guide_profile(target_id uuid default null)
returns jsonb
language sql stable security definer set search_path = public as $$
  select to_jsonb(gi) from public.guide_info gi
  where gi.id = coalesce(target_id, auth.uid())
$$;

create or replace function public.review_guide(
  guide_id uuid,
  rating numeric,
  review_text text default null
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  review_id uuid;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  insert into public.guide_reviews (guide_id, reviewer_id, rating, review_text)
  values (review_guide.guide_id, uid, review_guide.rating, review_guide.review_text)
  returning id into review_id;
  update public.guides g
  set avg_rating = (
    select coalesce(avg(r.rating), 0)
    from public.guide_reviews r
    where r.guide_id = g.id
  )
  where g.id = review_guide.guide_id;
  return review_id;
end $$;

create or replace function public.get_guides_for_destination(
  lat double precision,
  lon double precision,
  result_limit int default 20
)
returns setof public.guide_info
language sql stable security definer set search_path = public as $$
  select gi.*
  from public.guide_info gi
  join public.guide_service_areas sa on sa.guide_id = gi.id
  where st_dwithin(
    sa.location,
    st_setsrid(st_makepoint(lon, lat), 4326)::geography,
    sa.radius_meters
  )
  and (gi->>'is_available')::boolean = true
  and (gi->>'is_suspended')::boolean = false
  order by gi.avg_rating desc
  limit result_limit
$$;

create or replace function public.get_suspended_guides()
returns jsonb
language sql stable security definer set search_path = public as $$
  select coalesce(jsonb_agg(to_jsonb(sg) order by sg.suspended_at desc), '[]'::jsonb)
  from public.suspended_guides sg
  where sg.lifted_at is null
$$;

-- ==== sql/rpc/users.sql ====
-- Users module RPCs.

create or replace function public.fetch_profile(target_id uuid default null)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  resolved_id uuid := coalesce(target_id, auth.uid());
  result jsonb;
begin
  if resolved_id is null then
    raise exception 'not authenticated';
  end if;
  select to_jsonb(p) into result from public.profiles p where p.id = resolved_id;
  if result is null then
    raise exception 'profile not found';
  end if;
  -- Redact home_location into lat/lon jsonb for the client.
  if result ? 'home_location' then
    result := jsonb_set(
      result,
      '{home_location}',
      case
        when (select home_location is null from public.profiles where id = resolved_id) then 'null'::jsonb
        else (
          select jsonb_build_object(
            'latitude', st_y(home_location::geometry),
            'longitude', st_x(home_location::geometry)
          )
          from public.profiles where id = resolved_id
        )
      end
    );
  end if;
  return result;
end $$;

create or replace function public.is_username_available(username text)
returns boolean
language sql stable security definer set search_path = public as $$
  select not exists (select 1 from public.profiles p where p.username = is_username_available.username);
$$;

create or replace function public.complete_onbording(
  first_name text,
  last_name text,
  username text,
  middle_name text default null,
  phone_number text default null,
  emergency_contact text default null,
  avatar_url text default null,
  home_location jsonb default null,
  home_location_name text default null
)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  uid uuid := auth.uid();
  home geography;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  if home_location is not null then
    home := st_setsrid(
      st_makepoint(
        (home_location->>'longitude')::double precision,
        (home_location->>'latitude')::double precision
      ),
      4326
    )::geography;
  end if;
  insert into public.profiles (
    id, first_name, middle_name, last_name, username,
    phone_number, emergency_contact, avatar_url,
    home_location, home_location_name, is_onboarding_complete
  )
  values (
    uid, first_name, middle_name, last_name, username,
    phone_number, emergency_contact, avatar_url,
    home, home_location_name, true
  )
  on conflict (id) do update set
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    username = excluded.username,
    phone_number = excluded.phone_number,
    emergency_contact = excluded.emergency_contact,
    avatar_url = excluded.avatar_url,
    home_location = excluded.home_location,
    home_location_name = excluded.home_location_name,
    is_onboarding_complete = true,
    updated_at = now();
  return public.fetch_profile(uid);
end $$;

-- ==== sql/admin/rpc/admin_analytics.sql ====
-- Admin analytics RPCs.

create or replace function public.build_admin_analytics_payload(days int default 30)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare result jsonb;
begin
  perform public._assert_admin();
  select jsonb_build_object(
    'id', uuid_generate_v4(),
    'type', 'system_overview',
    'payload', jsonb_build_object(
      'window_days', days,
      'total_users', (select count(*) from public.profiles),
      'new_users', (
        select count(*) from public.profiles
        where created_at > now() - (days || ' days')::interval
      ),
      'new_bookings', (
        select count(*) from public.guide_bookings
        where hired_at > now() - (days || ' days')::interval
      ),
      'payment_volume', (
        select coalesce(sum(amount), 0) from public.payment_logs
        where status = 'succeeded'
          and created_at > now() - (days || ' days')::interval
      )
    ),
    'captured_at', now()
  ) into result;
  return result;
end $$;

create or replace function public.capture_admin_analytics_snapshot(
  type text,
  days int default 30
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare
  new_id uuid;
  payload jsonb;
begin
  perform public._assert_admin();
  payload := public.build_admin_analytics_payload(days);
  insert into public.admin_analytics (type, payload)
  values (type, payload)
  returning id into new_id;
  return new_id;
end $$;

create or replace function public.capture_all_admin_analytics_snapshots()
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  types text[] := array['system_overview'];
  t text;
  ids uuid[] := '{}';
begin
  perform public._assert_admin();
  foreach t in array types loop
    ids := ids || public.capture_admin_analytics_snapshot(t);
  end loop;
  return jsonb_build_object('captured_ids', to_jsonb(ids));
end $$;

create or replace function public.run_admin_analytics_midnight_job()
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public.capture_all_admin_analytics_snapshots();
end $$;

create or replace function public.schedule_admin_analytics_midnight_job()
returns text
language plpgsql security definer set search_path = public as $$
begin
  perform cron.schedule(
    'admin_analytics_midnight',
    '0 0 * * *',
    $job$ select public.run_admin_analytics_midnight_job(); $job$
  );
  return 'admin_analytics_midnight';
end $$;

-- ==== sql/admin/rpc/admin_crud.sql ====
-- Admin CRUD RPCs. All require is_admin = true on caller's profile.

create or replace function public._assert_admin()
returns void
language plpgsql security definer set search_path = public as $$
declare is_admin boolean;
begin
  select p.is_admin into is_admin from public.profiles p where p.id = auth.uid();
  if not coalesce(is_admin, false) then
    raise exception 'admin required';
  end if;
end $$;

create or replace function public.admin_create_base_destination(
  name text,
  coordinates jsonb,
  radius double precision,
  description text default '',
  tags text[] default '{}',
  feature_image text default null,
  additional_images text[] default '{}',
  possible_activities uuid[] default '{}'
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare new_id uuid;
begin
  perform public._assert_admin();
  insert into public.base_destination (
    name, coordinates, radius, description, tags,
    feature_image, additional_images, possible_activities
  )
  values (
    name,
    st_setsrid(
      st_makepoint(
        (coordinates->>'longitude')::double precision,
        (coordinates->>'latitude')::double precision
      ),
      4326
    )::geography,
    radius, description, tags, feature_image, additional_images, possible_activities
  )
  returning id into new_id;
  return new_id;
end $$;

create or replace function public.admin_update_base_destination(
  target_id uuid,
  name text default null,
  coordinates jsonb default null,
  radius double precision default null,
  description text default null,
  tags text[] default null,
  feature_image text default null,
  additional_images text[] default null,
  possible_activities uuid[] default null
)
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public._assert_admin();
  update public.base_destination
  set
    name = coalesce(admin_update_base_destination.name, name),
    coordinates = case
      when admin_update_base_destination.coordinates is null then coordinates
      else st_setsrid(
        st_makepoint(
          (admin_update_base_destination.coordinates->>'longitude')::double precision,
          (admin_update_base_destination.coordinates->>'latitude')::double precision
        ),
        4326
      )::geography
    end,
    radius = coalesce(admin_update_base_destination.radius, radius),
    description = coalesce(admin_update_base_destination.description, description),
    tags = coalesce(admin_update_base_destination.tags, tags),
    feature_image = coalesce(admin_update_base_destination.feature_image, feature_image),
    additional_images = coalesce(admin_update_base_destination.additional_images, additional_images),
    possible_activities = coalesce(admin_update_base_destination.possible_activities, possible_activities),
    updated_at = now()
  where id = target_id;
end $$;

create or replace function public.admin_delete_base_destination(target_id uuid)
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public._assert_admin();
  delete from public.base_destination where id = target_id;
end $$;

create or replace function public.admin_create_activity(
  name text,
  icon text default null,
  description text default null,
  feature_image text default null
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare new_id uuid;
begin
  perform public._assert_admin();
  insert into public.activities (name, icon, description, feature_image)
  values (name, icon, description, feature_image)
  returning id into new_id;
  return new_id;
end $$;

create or replace function public.admin_update_activity(
  target_id uuid,
  name text default null,
  icon text default null,
  description text default null,
  feature_image text default null
)
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public._assert_admin();
  update public.activities
  set
    name = coalesce(admin_update_activity.name, name),
    icon = coalesce(admin_update_activity.icon, icon),
    description = coalesce(admin_update_activity.description, description),
    feature_image = coalesce(admin_update_activity.feature_image, feature_image)
  where id = target_id;
end $$;

create or replace function public.admin_delete_activity(target_id uuid)
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public._assert_admin();
  delete from public.activities where id = target_id;
end $$;

create or replace function public.admin_create_travel_package(
  name text,
  type travel_package_type,
  actual_price numeric,
  total_days int,
  description text default '',
  discounted_price numeric default null,
  discount_deadline timestamptz default null,
  expiration_date timestamptz default null,
  featured_image text default null,
  additional_images text[] default '{}',
  travel_routes text[] default '{}',
  destinations_covered uuid[] default '{}',
  included_activities uuid[] default '{}',
  main_activity uuid default null
)
returns uuid
language plpgsql security definer set search_path = public as $$
declare new_id uuid;
begin
  perform public._assert_admin();
  insert into public.travel_packages (
    name, type, actual_price, discounted_price, discount_deadline, expiration_date,
    featured_image, additional_images, total_days, travel_routes,
    description, destinations_covered, included_activities, main_activity
  )
  values (
    name, type, actual_price, discounted_price, discount_deadline, expiration_date,
    featured_image, additional_images, total_days, travel_routes,
    description, destinations_covered, included_activities, main_activity
  )
  returning id into new_id;
  return new_id;
end $$;

create or replace function public.admin_update_travel_package(
  target_id uuid,
  name text default null,
  type travel_package_type default null,
  actual_price numeric default null,
  discounted_price numeric default null,
  discount_deadline timestamptz default null,
  expiration_date timestamptz default null,
  featured_image text default null,
  additional_images text[] default null,
  total_days int default null,
  travel_routes text[] default null,
  description text default null,
  destinations_covered uuid[] default null,
  included_activities uuid[] default null,
  main_activity uuid default null
)
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public._assert_admin();
  update public.travel_packages
  set
    name = coalesce(admin_update_travel_package.name, name),
    type = coalesce(admin_update_travel_package.type, type),
    actual_price = coalesce(admin_update_travel_package.actual_price, actual_price),
    discounted_price = coalesce(admin_update_travel_package.discounted_price, discounted_price),
    discount_deadline = coalesce(admin_update_travel_package.discount_deadline, discount_deadline),
    expiration_date = coalesce(admin_update_travel_package.expiration_date, expiration_date),
    featured_image = coalesce(admin_update_travel_package.featured_image, featured_image),
    additional_images = coalesce(admin_update_travel_package.additional_images, additional_images),
    total_days = coalesce(admin_update_travel_package.total_days, total_days),
    travel_routes = coalesce(admin_update_travel_package.travel_routes, travel_routes),
    description = coalesce(admin_update_travel_package.description, description),
    destinations_covered = coalesce(admin_update_travel_package.destinations_covered, destinations_covered),
    included_activities = coalesce(admin_update_travel_package.included_activities, included_activities),
    main_activity = coalesce(admin_update_travel_package.main_activity, main_activity),
    updated_at = now()
  where id = target_id;
end $$;

create or replace function public.admin_delete_travel_package(target_id uuid)
returns void
language plpgsql security definer set search_path = public as $$
begin
  perform public._assert_admin();
  delete from public.travel_packages where id = target_id;
end $$;

create or replace function public.change_guide_application_status(
  application_id uuid,
  new_status guide_application_status,
  feedback text default null
)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  app record;
begin
  perform public._assert_admin();
  update public.guide_applications
  set status = new_status,
      admin_feedback = feedback,
      updated_at = now()
  where id = application_id
  returning * into app;

  if new_status = 'approved' then
    insert into public.guides (id, description, previous_experience, known_languages)
    values (app.applicant_id, app.description, app.previous_experience, app.known_languages)
    on conflict (id) do update
      set description = excluded.description,
          previous_experience = excluded.previous_experience,
          known_languages = excluded.known_languages,
          is_suspended = false,
          updated_at = now();
    update public.profiles
    set is_guide = true, is_guide_applicantion_pending = false, updated_at = now()
    where id = app.applicant_id;
  elsif new_status in ('rejected', 'revision_requested') then
    update public.profiles
    set is_guide_applicantion_pending = (new_status = 'revision_requested'),
        updated_at = now()
    where id = app.applicant_id;
  end if;

  return to_jsonb(app);
end $$;

create or replace function public.change_guide_suspend_status(
  guide_id uuid,
  suspend boolean,
  reason text default null
)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare suspension_id uuid;
begin
  perform public._assert_admin();
  update public.guides set is_suspended = suspend, updated_at = now() where id = guide_id;
  if suspend then
    insert into public.suspended_guides (guide_id, reason, suspended_by)
    values (guide_id, coalesce(reason, ''), auth.uid())
    returning id into suspension_id;
  else
    update public.suspended_guides
    set lifted_at = now()
    where guide_id = change_guide_suspend_status.guide_id and lifted_at is null;
  end if;
  return jsonb_build_object('guide_id', guide_id, 'suspended', suspend);
end $$;

-- TRIGGERS
-- AUTOGENERATED by sql/sql-gen.sh. DO NOT EDIT.

-- ==== sql/triggers/base.sql ====
-- Shared triggers.

create or replace function public.tg_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

-- Attach to every table that has an updated_at column.
do $$
declare r record;
begin
  for r in
    select table_schema, table_name
    from information_schema.columns
    where column_name = 'updated_at' and table_schema = 'public'
  loop
    execute format(
      'drop trigger if exists %I_updated_at on %I.%I',
      r.table_name, r.table_schema, r.table_name
    );
    execute format(
      'create trigger %I_updated_at before update on %I.%I for each row execute function public.tg_updated_at()',
      r.table_name, r.table_schema, r.table_name
    );
  end loop;
end $$;

-- Maintain stories.like_count / comment_count.
create or replace function public.tg_story_like_count()
returns trigger language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    update public.stories set like_count = like_count + 1 where id = new.story_id;
  elsif tg_op = 'DELETE' then
    update public.stories set like_count = greatest(like_count - 1, 0) where id = old.story_id;
  end if;
  return null;
end $$;

drop trigger if exists story_like_count_trg on public.story_likes;
create trigger story_like_count_trg
after insert or delete on public.story_likes
for each row execute function public.tg_story_like_count();

create or replace function public.tg_story_comment_count()
returns trigger language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    update public.stories set comment_count = comment_count + 1 where id = new.story_id;
  elsif tg_op = 'DELETE' then
    update public.stories set comment_count = greatest(comment_count - 1, 0) where id = old.story_id;
  end if;
  return null;
end $$;

drop trigger if exists story_comment_count_trg on public.story_comments;
create trigger story_comment_count_trg
after insert or delete on public.story_comments
for each row execute function public.tg_story_comment_count();

-- RLS
-- AUTOGENERATED by sql/sql-gen.sh. DO NOT EDIT.

-- ==== sql/rls/base.sql ====
-- Base RLS policies. Admins bypass via a policy matching is_admin = true.

alter table public.profiles enable row level security;
alter table public.base_destination enable row level security;
alter table public.base_destination_reviews enable row level security;
alter table public.activities enable row level security;
alter table public.travel_packages enable row level security;
alter table public.guides enable row level security;
alter table public.guide_service_areas enable row level security;
alter table public.guide_reviews enable row level security;
alter table public.suspended_guides enable row level security;
alter table public.stories enable row level security;
alter table public.story_likes enable row level security;
alter table public.story_comments enable row level security;
alter table public.photos enable row level security;
alter table public.hiring_proposals enable row level security;
alter table public.guide_bookings enable row level security;
alter table public.package_bookings enable row level security;
alter table public.payment_logs enable row level security;
alter table public.guide_applications enable row level security;
alter table public.guide_service_areas_applications enable row level security;
alter table public.unsuspension_requests enable row level security;

-- Helper: is caller an admin?
create or replace function public.is_admin()
returns boolean
language sql stable security definer set search_path = public as $$
  select coalesce((select is_admin from public.profiles where id = auth.uid()), false)
$$;

-- profiles
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select using (true);

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update using (
  id = auth.uid() or public.is_admin()
);

-- base_destination (read public; write admin via RPC)
drop policy if exists dest_select on public.base_destination;
create policy dest_select on public.base_destination for select using (true);

-- activities
drop policy if exists activities_select on public.activities;
create policy activities_select on public.activities for select using (true);

-- travel_packages
drop policy if exists packages_select on public.travel_packages;
create policy packages_select on public.travel_packages for select using (true);

-- guides / service areas (public read when not suspended)
drop policy if exists guides_select on public.guides;
create policy guides_select on public.guides for select using (true);

drop policy if exists guide_sa_select on public.guide_service_areas;
create policy guide_sa_select on public.guide_service_areas for select using (true);

-- reviews (public read, authenticated insert)
drop policy if exists dest_reviews_select on public.base_destination_reviews;
create policy dest_reviews_select on public.base_destination_reviews for select using (true);

drop policy if exists dest_reviews_insert on public.base_destination_reviews;
create policy dest_reviews_insert on public.base_destination_reviews for insert with check (
  auth.uid() is not null and reviewer_id = auth.uid()
);

drop policy if exists guide_reviews_select on public.guide_reviews;
create policy guide_reviews_select on public.guide_reviews for select using (true);

-- stories (public read non-archived, owner + admin write)
drop policy if exists stories_select on public.stories;
create policy stories_select on public.stories for select using (
  visibility <> 'archived' or author_id = auth.uid() or public.is_admin()
);

drop policy if exists stories_owner_write on public.stories;
create policy stories_owner_write on public.stories for all using (
  author_id = auth.uid() or public.is_admin()
) with check (
  author_id = auth.uid() or public.is_admin()
);

-- photos
drop policy if exists photos_select on public.photos;
create policy photos_select on public.photos for select using (true);

drop policy if exists photos_owner_write on public.photos;
create policy photos_owner_write on public.photos for all using (
  uploader_id = auth.uid() or public.is_admin()
) with check (
  uploader_id = auth.uid() or public.is_admin()
);

-- hiring_proposals / bookings: participants + admin read
drop policy if exists proposal_participant_select on public.hiring_proposals;
create policy proposal_participant_select on public.hiring_proposals for select using (
  tourist_id = auth.uid() or guide_id = auth.uid() or public.is_admin()
);

drop policy if exists booking_participant_select on public.guide_bookings;
create policy booking_participant_select on public.guide_bookings for select using (
  tourist_id = auth.uid() or guide_id = auth.uid() or public.is_admin()
);

drop policy if exists package_booking_participant_select on public.package_bookings;
create policy package_booking_participant_select on public.package_bookings for select using (
  tourist_id = auth.uid() or public.is_admin()
);

drop policy if exists payment_logs_select on public.payment_logs;
create policy payment_logs_select on public.payment_logs for select using (
  tourist_id = auth.uid() or public.is_admin()
);

-- applications: applicant + admin
drop policy if exists applications_select on public.guide_applications;
create policy applications_select on public.guide_applications for select using (
  applicant_id = auth.uid() or public.is_admin()
);

drop policy if exists application_areas_select on public.guide_service_areas_applications;
create policy application_areas_select on public.guide_service_areas_applications for select using (
  exists (
    select 1 from public.guide_applications ga
    where ga.id = application_id
      and (ga.applicant_id = auth.uid() or public.is_admin())
  )
);

drop policy if exists unsuspension_select on public.unsuspension_requests;
create policy unsuspension_select on public.unsuspension_requests for select using (
  guide_id = auth.uid() or public.is_admin()
);

-- ==== sql/admin/rls/admin.sql ====
-- Admin-only RLS policies.

alter table public.admin_analytics enable row level security;

drop policy if exists admin_analytics_admin_all on public.admin_analytics;
create policy admin_analytics_admin_all on public.admin_analytics
  for all using (public.is_admin()) with check (public.is_admin());

