-- AUTOGENERATED by sql/sql-gen.sh. DO NOT EDIT.

-- ==== sql/schema/00_extensions.sql ====
-- Required Postgres extensions.

create extension if not exists "uuid-ossp";
create extension if not exists postgis;
create extension if not exists pg_cron;

-- ==== sql/schema/01_enums.sql ====
-- Platform-wide enums. Keep in sync with backend/v2/schemas/enums.ts.

do $$ begin
  create type hiring_proposal_status as enum (
    'sent_by_tourist',
    'offered_by_guide',
    'rejected_by_guide',
    'cancelled_by_tourist',
    'accepted_by_tourist'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type booking_status as enum (
    'pending_payment',
    'confirmed',
    'in_progress',
    'completed',
    'cancelled',
    'disputed'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type payment_status as enum (
    'pending',
    'succeeded',
    'failed',
    'refunded'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type guide_application_status as enum (
    'pending',
    'approved',
    'rejected',
    'revision_requested'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type unsuspension_request_status as enum (
    'pending',
    'approved',
    'rejected'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type travel_package_type as enum ('destination', 'activity');
exception when duplicate_object then null; end $$;

do $$ begin
  create type story_visibility as enum ('public', 'unlisted', 'archived');
exception when duplicate_object then null; end $$;

-- ==== sql/schema/10_profiles.sql ====
-- Users module.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  middle_name text,
  last_name text,
  username text not null unique,
  phone_number text,
  emergency_contact text,
  avatar_url text,
  is_admin boolean not null default false,
  is_guide boolean not null default false,
  is_guide_applicantion_pending boolean not null default false,
  is_onboarding_complete boolean not null default false,
  home_location geography(point, 4326),
  home_location_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_username_idx on public.profiles (username);
create index if not exists profiles_home_location_idx
  on public.profiles using gist (home_location);

-- ==== sql/schema/20_destinations.sql ====
-- Destinations module.

create table if not exists public.base_destination (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  coordinates geography(point, 4326) not null,
  radius double precision not null check (radius > 0),
  avg_rating numeric(3, 2) not null default 0,
  tags text[] not null default '{}',
  description text not null default '',
  feature_image text,
  additional_images text[] not null default '{}',
  possible_activities uuid[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists base_destination_coords_idx
  on public.base_destination using gist (coordinates);

create table if not exists public.base_destination_reviews (
  id uuid primary key default uuid_generate_v4(),
  destination_id uuid not null references public.base_destination(id) on delete cascade,
  reviewer_id uuid not null references public.profiles(id) on delete cascade,
  rating numeric(3, 2) not null check (rating between 0 and 5),
  review_text text,
  created_at timestamptz not null default now()
);

create table if not exists public.activities (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  icon text,
  description text,
  feature_image text,
  created_at timestamptz not null default now()
);

create table if not exists public.travel_packages (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  type travel_package_type not null,
  actual_price numeric(12, 2) not null check (actual_price >= 0),
  discounted_price numeric(12, 2),
  discount_deadline timestamptz,
  expiration_date timestamptz,
  featured_image text,
  additional_images text[] not null default '{}',
  total_days int not null check (total_days > 0),
  travel_routes text[] not null default '{}',
  description text not null default '',
  destinations_covered uuid[] not null default '{}',
  included_activities uuid[] not null default '{}',
  main_activity uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ==== sql/schema/30_guides.sql ====
-- Guides module.

create table if not exists public.guides (
  id uuid primary key references public.profiles(id) on delete cascade,
  description text not null default '',
  previous_experience text,
  known_languages text[] not null default '{}',
  admin_feedback text,
  is_available boolean not null default true,
  is_suspended boolean not null default false,
  avg_rating numeric(3, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guide_service_areas (
  id uuid primary key default uuid_generate_v4(),
  guide_id uuid not null references public.guides(id) on delete cascade,
  location geography(point, 4326) not null,
  radius_meters double precision not null check (radius_meters > 0),
  location_name text not null
);
create index if not exists guide_service_areas_loc_idx
  on public.guide_service_areas using gist (location);

create table if not exists public.guide_reviews (
  id uuid primary key default uuid_generate_v4(),
  guide_id uuid not null references public.guides(id) on delete cascade,
  reviewer_id uuid not null references public.profiles(id) on delete cascade,
  rating numeric(3, 2) not null check (rating between 0 and 5),
  review_text text,
  created_at timestamptz not null default now()
);

create table if not exists public.suspended_guides (
  id uuid primary key default uuid_generate_v4(),
  guide_id uuid not null references public.guides(id) on delete cascade,
  reason text not null,
  suspended_at timestamptz not null default now(),
  suspended_by uuid not null references public.profiles(id),
  lifted_at timestamptz
);

-- ==== sql/schema/40_stories.sql ====
-- Stories & photos module.

create table if not exists public.stories (
  id uuid primary key default uuid_generate_v4(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  content text not null default '',
  feature_image text,
  tags text[] not null default '{}',
  categories text[] not null default '{}',
  location geography(point, 4326),
  location_name text,
  visibility story_visibility not null default 'public',
  like_count int not null default 0,
  comment_count int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.story_likes (
  story_id uuid not null references public.stories(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (story_id, user_id)
);

create table if not exists public.story_comments (
  id uuid primary key default uuid_generate_v4(),
  story_id uuid not null references public.stories(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.photos (
  id uuid primary key default uuid_generate_v4(),
  uploader_id uuid not null references public.profiles(id) on delete cascade,
  image_url text not null,
  description text,
  location geography(point, 4326),
  location_name text,
  created_at timestamptz not null default now()
);

-- ==== sql/schema/50_bookings.sql ====
-- Bookings module.

create table if not exists public.hiring_proposals (
  id uuid primary key default uuid_generate_v4(),
  tourist_id uuid not null references public.profiles(id) on delete cascade,
  guide_id uuid not null references public.guides(id) on delete cascade,
  destinations uuid[] not null default '{}',
  people_count int not null check (people_count > 0),
  duration_days int not null check (duration_days > 0),
  total_quoted_price numeric(12, 2),
  prepay_required numeric(12, 2),
  status hiring_proposal_status not null default 'sent_by_tourist',
  tourist_remarks text,
  guide_remarks text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guide_bookings (
  id uuid primary key default uuid_generate_v4(),
  proposal_id uuid not null references public.hiring_proposals(id) on delete cascade,
  tourist_id uuid not null references public.profiles(id) on delete cascade,
  guide_id uuid not null references public.guides(id) on delete cascade,
  final_amount numeric(12, 2) not null,
  prepay_amount numeric(12, 2) not null,
  paid_amount numeric(12, 2) not null default 0,
  status booking_status not null default 'pending_payment',
  trip_start_date timestamptz,
  hired_at timestamptz not null default now()
);

create table if not exists public.package_bookings (
  id uuid primary key default uuid_generate_v4(),
  package_id uuid not null references public.travel_packages(id) on delete cascade,
  tourist_id uuid not null references public.profiles(id) on delete cascade,
  people_count int not null check (people_count > 0),
  total_amount numeric(12, 2) not null,
  paid_amount numeric(12, 2) not null default 0,
  status booking_status not null default 'pending_payment',
  trip_start_date timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.payment_logs (
  id uuid primary key default uuid_generate_v4(),
  guide_booking_id uuid references public.guide_bookings(id) on delete set null,
  package_booking_id uuid references public.package_bookings(id) on delete set null,
  tourist_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null,
  provider_txn_id text not null,
  amount numeric(12, 2) not null,
  currency text not null default 'NPR',
  status payment_status not null default 'pending',
  raw_response jsonb,
  created_at timestamptz not null default now(),
  check (guide_booking_id is not null or package_booking_id is not null)
);

-- ==== sql/schema/60_applications.sql ====
-- Applications module.

create table if not exists public.guide_applications (
  id uuid primary key default uuid_generate_v4(),
  applicant_id uuid not null references public.profiles(id) on delete cascade,
  description text not null default '',
  previous_experience text,
  known_languages text[] not null default '{}',
  status guide_application_status not null default 'pending',
  admin_feedback text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guide_service_areas_applications (
  id uuid primary key default uuid_generate_v4(),
  application_id uuid not null references public.guide_applications(id) on delete cascade,
  location geography(point, 4326) not null,
  radius_meters double precision not null check (radius_meters > 0),
  location_name text not null
);

create table if not exists public.unsuspension_requests (
  id uuid primary key default uuid_generate_v4(),
  guide_id uuid not null references public.guides(id) on delete cascade,
  reason text not null,
  status unsuspension_request_status not null default 'pending',
  admin_feedback text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ==== sql/admin/schema/00_admin_tables.sql ====
-- Admin-only tables (isolated from main schema for clarity).

create table if not exists public.admin_analytics (
  id uuid primary key default uuid_generate_v4(),
  type text not null,
  payload jsonb not null,
  captured_at timestamptz not null default now()
);

create index if not exists admin_analytics_type_idx
  on public.admin_analytics (type, captured_at desc);

