-- AUTOGENERATED by sql/sql-gen.sh. DO NOT EDIT.

-- ==== sql/views/bookings.sql ====
-- Bookings module read views.

create or replace view public.guide_booking_requests as
  select
    hp.*
  from public.hiring_proposals hp;

create or replace view public.guide_bookings_info as
  select
    gb.*,
    coalesce(
      (
        select jsonb_agg(to_jsonb(pl) order by pl.created_at)
        from public.payment_logs pl
        where pl.guide_booking_id = gb.id
      ),
      '[]'::jsonb
    ) as payments
  from public.guide_bookings gb;

create or replace view public.package_bookings_info as
  select
    pb.*,
    coalesce(
      (
        select jsonb_agg(to_jsonb(pl) order by pl.created_at)
        from public.payment_logs pl
        where pl.package_booking_id = pb.id
      ),
      '[]'::jsonb
    ) as payments
  from public.package_bookings pb;

-- ==== sql/views/destinations.sql ====
-- Destinations module read views.

create or replace view public.destinations as
  select
    d.id,
    d.name,
    jsonb_build_object(
      'latitude', st_y(d.coordinates::geometry),
      'longitude', st_x(d.coordinates::geometry)
    ) as coordinates,
    d.radius,
    d.avg_rating,
    d.tags,
    d.description,
    d.feature_image,
    d.additional_images,
    d.possible_activities,
    d.created_at,
    d.updated_at,
    coalesce(
      (
        select jsonb_agg(jsonb_build_object('id', a.id, 'name', a.name, 'icon', a.icon))
        from public.activities a
        where a.id = any(d.possible_activities)
      ),
      '[]'::jsonb
    ) as activities
  from public.base_destination d;

create or replace view public.destination_reviews as
  select
    r.id,
    r.destination_id,
    r.reviewer_id,
    r.rating,
    r.review_text,
    r.created_at,
    p.username as reviewer_username,
    p.avatar_url as reviewer_avatar_url
  from public.base_destination_reviews r
  left join public.profiles p on p.id = r.reviewer_id;

create or replace view public.available_activities as
  select * from public.activities order by name asc;

create or replace view public.destination_packages as
  select * from public.travel_packages
  where type = 'destination'
    and (expiration_date is null or expiration_date > now());

create or replace view public.activities_packages as
  select * from public.travel_packages
  where type = 'activity'
    and (expiration_date is null or expiration_date > now());

-- ==== sql/views/guides.sql ====
-- Guides module read views.

create or replace view public.guide_info as
  select
    g.id,
    g.description,
    g.previous_experience,
    g.known_languages,
    g.admin_feedback,
    g.is_available,
    g.is_suspended,
    g.avg_rating,
    g.created_at,
    g.updated_at,
    jsonb_build_object(
      'id', p.id,
      'username', p.username,
      'first_name', p.first_name,
      'last_name', p.last_name,
      'avatar_url', p.avatar_url
    ) as user,
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'id', sa.id,
            'guide_id', sa.guide_id,
            'location', jsonb_build_object(
              'latitude', st_y(sa.location::geometry),
              'longitude', st_x(sa.location::geometry)
            ),
            'radius_meters', sa.radius_meters,
            'location_name', sa.location_name
          )
        )
        from public.guide_service_areas sa
        where sa.guide_id = g.id
      ),
      '[]'::jsonb
    ) as service_areas
  from public.guides g
  join public.profiles p on p.id = g.id;

create or replace view public.available_guides as
  select * from public.guide_info
  where is_available = true and is_suspended = false;

-- ==== sql/views/stories.sql ====
-- Stories & photos module read views.

create or replace view public.stories_info as
  select
    s.id,
    s.author_id,
    s.title,
    s.content,
    s.feature_image,
    s.tags,
    s.categories,
    case
      when s.location is null then null
      else jsonb_build_object(
        'latitude', st_y(s.location::geometry),
        'longitude', st_x(s.location::geometry)
      )
    end as location,
    s.location_name,
    s.visibility,
    s.like_count,
    s.comment_count,
    s.created_at,
    s.updated_at,
    jsonb_build_object(
      'id', p.id,
      'username', p.username,
      'first_name', p.first_name,
      'last_name', p.last_name,
      'avatar_url', p.avatar_url
    ) as author
  from public.stories s
  left join public.profiles p on p.id = s.author_id;

create or replace view public.photos_info as
  select
    ph.id,
    ph.uploader_id,
    ph.image_url,
    ph.description,
    case
      when ph.location is null then null
      else jsonb_build_object(
        'latitude', st_y(ph.location::geometry),
        'longitude', st_x(ph.location::geometry)
      )
    end as location,
    ph.location_name,
    ph.created_at,
    jsonb_build_object(
      'id', p.id,
      'username', p.username,
      'first_name', p.first_name,
      'last_name', p.last_name,
      'avatar_url', p.avatar_url
    ) as uploader
  from public.photos ph
  left join public.profiles p on p.id = ph.uploader_id;

-- ==== sql/views/users.sql ====
-- Users module read views.

create or replace view public.user_info as
  select
    p.id,
    p.username,
    p.first_name,
    p.middle_name,
    p.last_name,
    p.avatar_url,
    p.is_admin,
    p.is_guide,
    p.is_onboarding_complete,
    p.home_location_name,
    p.created_at
  from public.profiles p;

create or replace view public.minimal_user as
  select
    p.id,
    p.username,
    p.first_name,
    p.last_name,
    p.avatar_url
  from public.profiles p;

-- ==== sql/admin/views/admin.sql ====
-- Admin-only read views. Always filter behind RLS to admins.

create or replace view public.admin_pending_guide_applications as
  select
    ga.*,
    jsonb_build_object(
      'id', p.id,
      'username', p.username,
      'first_name', p.first_name,
      'last_name', p.last_name
    ) as applicant
  from public.guide_applications ga
  left join public.profiles p on p.id = ga.applicant_id
  where ga.status = 'pending'
  order by ga.created_at asc;

create or replace view public.admin_pending_unsuspension_requests as
  select
    ur.*,
    jsonb_build_object(
      'id', p.id,
      'username', p.username,
      'first_name', p.first_name,
      'last_name', p.last_name
    ) as guide
  from public.unsuspension_requests ur
  left join public.profiles p on p.id = ur.guide_id
  where ur.status = 'pending'
  order by ur.created_at asc;

create or replace view public.admin_booking_negotiation_queue as
  select * from public.hiring_proposals
  where status in ('sent_by_tourist', 'offered_by_guide')
  order by updated_at desc;

create or replace view public.admin_payment_review_queue as
  select * from public.payment_logs
  where status = 'pending'
  order by created_at asc;

create or replace view public.admin_package_health_queue as
  select * from public.travel_packages
  where expiration_date is not null
    and expiration_date > now()
    and expiration_date < now() + interval '7 days'
  order by expiration_date asc;

create or replace view public.admin_package_booking_requests as
  select pb.*,
         tp.name as package_name
  from public.package_bookings pb
  join public.travel_packages tp on tp.id = pb.package_id
  where pb.status = 'pending_payment'
  order by pb.created_at desc;

create or replace view public.admin_system_overview as
  select
    (select count(*) from public.profiles) as total_users,
    (select count(*) from public.guides where is_suspended = false) as total_guides,
    (select count(*) from public.guide_applications where status = 'pending') as pending_guide_applications,
    (select count(*) from public.guide_bookings
      where status in ('pending_payment', 'confirmed', 'in_progress')) as active_bookings,
    (select count(*) from public.payment_logs where status = 'pending') as pending_payment_reviews,
    (select count(*) from public.guides where is_suspended = true) as suspended_guides;

