
/*
============================================================
AUTO-GENERATED FILE: full-rls.sql
Generated at: 2026-04-20 16:02:52.873278Z
Source: All .sql files in rls directory

DO NOT EDIT MANUALLY - EDIT THE SOURCE SQL FILES INSTEAD

Description: This file contains the combined SQL.
Generated by sql-gen.dart script
============================================================
*/



-- FILE: rls/admin-analytics-rls.sql
ALTER TABLE public.admin_analytics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_analytics_admin_read_only" ON public.admin_analytics;

CREATE POLICY "admin_analytics_admin_read_only"
ON public.admin_analytics
FOR SELECT
USING (public.current_user_is_admin());


-- FILE: rls/bookings-rls.sql
ALTER TABLE public.hiring_proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guide_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.package_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "hiring_proposals_participant_select" ON public.hiring_proposals;
DROP POLICY IF EXISTS "hiring_proposals_tourist_insert" ON public.hiring_proposals;
DROP POLICY IF EXISTS "hiring_proposals_participant_update" ON public.hiring_proposals;
DROP POLICY IF EXISTS "hiring_proposals_admin_all" ON public.hiring_proposals;

DROP POLICY IF EXISTS "guide_bookings_participant_select" ON public.guide_bookings;
DROP POLICY IF EXISTS "guide_bookings_tourist_insert" ON public.guide_bookings;
DROP POLICY IF EXISTS "guide_bookings_admin_all" ON public.guide_bookings;

DROP POLICY IF EXISTS "package_bookings_owner_select" ON public.package_bookings;
DROP POLICY IF EXISTS "package_bookings_owner_insert" ON public.package_bookings;
DROP POLICY IF EXISTS "package_bookings_admin_all" ON public.package_bookings;

DROP POLICY IF EXISTS "payment_logs_participant_select" ON public.payment_logs;
DROP POLICY IF EXISTS "payment_logs_tourist_insert" ON public.payment_logs;
DROP POLICY IF EXISTS "payment_logs_admin_all" ON public.payment_logs;

CREATE POLICY "hiring_proposals_participant_select"
ON public.hiring_proposals
FOR SELECT
USING (
  auth.uid() = tourist_id
  OR auth.uid() = guide_id
  OR public.current_user_is_admin()
);

CREATE POLICY "hiring_proposals_admin_all"
ON public.hiring_proposals
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());

CREATE POLICY "guide_bookings_participant_select"
ON public.guide_bookings
FOR SELECT
USING (
  auth.uid() = tourist_id
  OR auth.uid() = guide_id
  OR public.current_user_is_admin()
);

CREATE POLICY "guide_bookings_admin_all"
ON public.guide_bookings
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());

CREATE POLICY "package_bookings_owner_select"
ON public.package_bookings
FOR SELECT
USING (public.current_user_is_admin());

CREATE POLICY "package_bookings_admin_all"
ON public.package_bookings
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());

CREATE POLICY "payment_logs_participant_select"
ON public.payment_logs
FOR SELECT
USING (
  auth.uid() = tourist_id
  OR EXISTS (
    SELECT 1
    FROM public.guide_bookings gb
    WHERE gb.id = payment_logs.guide_booking_id
      AND gb.guide_id = auth.uid()
  )
  OR public.current_user_is_admin()
);

CREATE POLICY "payment_logs_admin_all"
ON public.payment_logs
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());


-- FILE: rls/destinations-rls.sql
ALTER TABLE public.base_destination ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.base_destination_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "base_destination_public_select" ON public.base_destination;
DROP POLICY IF EXISTS "base_destination_admin_all" ON public.base_destination;

DROP POLICY IF EXISTS "base_destination_reviews_public_select" ON public.base_destination_reviews;
DROP POLICY IF EXISTS "base_destination_reviews_self_manage" ON public.base_destination_reviews;
DROP POLICY IF EXISTS "base_destination_reviews_admin_all" ON public.base_destination_reviews;

CREATE POLICY "base_destination_public_select"
ON public.base_destination
FOR SELECT
USING (true);

CREATE POLICY "base_destination_admin_all"
ON public.base_destination
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());

CREATE POLICY "base_destination_reviews_public_select"
ON public.base_destination_reviews
FOR SELECT
USING (true);

CREATE POLICY "base_destination_reviews_self_manage"
ON public.base_destination_reviews
FOR ALL
USING (tourist_id = auth.uid())
WITH CHECK (tourist_id = auth.uid());

CREATE POLICY "base_destination_reviews_admin_all"
ON public.base_destination_reviews
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());


-- FILE: rls/guides-rls.sql
ALTER TABLE public.guide_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guide_service_areas_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guide_service_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guide_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suspended_guides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unsuspension_requests ENABLE ROW LEVEL SECURITY;


CREATE POLICY "guide_applications_self_select"
ON public.guide_applications
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "guide_applications_admin_all"
ON public.guide_applications
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());

CREATE POLICY "guide_area_applications_self_manage"
ON public.guide_service_areas_applications
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.guide_applications ga
    WHERE ga.application_id = guide_service_areas_applications.application_id
      AND ga.user_id = auth.uid()
  )
);

CREATE POLICY "guide_area_applications_admin_all"
ON public.guide_service_areas_applications
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());

CREATE POLICY "guides_public_select"
ON public.guides
FOR SELECT
USING (true);

CREATE POLICY "guides_self_manage"
ON public.guides
FOR ALL
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

CREATE POLICY "guides_admin_all"
ON public.guides
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());

CREATE POLICY "guide_service_areas_public_select"
ON public.guide_service_areas
FOR SELECT
USING (true);

CREATE POLICY "guide_service_areas_self_manage"
ON public.guide_service_areas
FOR ALL
USING (auth.uid() = guide_id)
WITH CHECK (auth.uid() = guide_id);

CREATE POLICY "guide_service_areas_admin_all"
ON public.guide_service_areas
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());

CREATE POLICY "guide_reviews_public_select"
ON public.guide_reviews
FOR SELECT
USING (true);

CREATE POLICY "guide_reviews_self_manage"
ON public.guide_reviews
FOR ALL
USING (auth.uid() = reviewer_id)
WITH CHECK (auth.uid() = reviewer_id);

CREATE POLICY "guide_reviews_admin_all"
ON public.guide_reviews
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());

CREATE POLICY "suspended_guides_owner_or_admin_select"
ON public.suspended_guides
FOR SELECT
USING (guide_id = auth.uid() OR public.current_user_is_admin());

CREATE POLICY "suspended_guides_admin_all"
ON public.suspended_guides
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());

CREATE POLICY "unsuspension_requests_owner_or_admin_select"
ON public.unsuspension_requests
FOR SELECT
USING (guide_id = auth.uid() OR public.current_user_is_admin());

CREATE POLICY "unsuspension_requests_owner_insert"
ON public.unsuspension_requests
FOR INSERT
WITH CHECK (guide_id = auth.uid());

CREATE POLICY "unsuspension_requests_owner_delete_pending"
ON public.unsuspension_requests
FOR DELETE
USING (guide_id = auth.uid() AND status = 'pending');

CREATE POLICY "unsuspension_requests_admin_all"
ON public.unsuspension_requests
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());


-- FILE: rls/packages-rls.sql
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.travel_packages ENABLE ROW LEVEL SECURITY;


CREATE POLICY "activities_public_select"
ON public.activities
FOR SELECT
USING (true);

CREATE POLICY "activities_admin_all"
ON public.activities
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());

CREATE POLICY "travel_packages_public_select"
ON public.travel_packages
FOR SELECT
USING (true);

CREATE POLICY "travel_packages_admin_all"
ON public.travel_packages
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());


-- FILE: rls/photos-rls.sql
ALTER TABLE public.photos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "photos_public_select"
ON public.photos
FOR SELECT
USING (true);

CREATE POLICY "photos_owner_manage"
ON public.photos
FOR ALL
USING (auth.uid() = uploader_id)
WITH CHECK (auth.uid() = uploader_id);

CREATE POLICY "photos_admin_all"
ON public.photos
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());


-- FILE: rls/storage-rls.sql
CREATE POLICY "storage_profile_pics_public_select"
ON storage.objects
FOR SELECT
USING (bucket_id = 'profile_pics');

CREATE POLICY "storage_profile_pics_owner_manage"
ON storage.objects
FOR ALL
USING (bucket_id = 'profile_pics' AND (storage.foldername(name))[1] = auth.uid()::text)
WITH CHECK (bucket_id = 'profile_pics' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "storage_profile_pics_admin_manage"
ON storage.objects
FOR ALL
USING (bucket_id = 'profile_pics' AND public.current_user_is_admin())
WITH CHECK (bucket_id = 'profile_pics' AND public.current_user_is_admin());

CREATE POLICY "storage_vault_owner_select"
ON storage.objects
FOR SELECT
USING (bucket_id = 'vault' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "storage_vault_owner_insert"
ON storage.objects
FOR INSERT
WITH CHECK (bucket_id = 'vault' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "storage_vault_owner_update_delete"
ON storage.objects
FOR UPDATE
USING (bucket_id = 'vault' AND (storage.foldername(name))[1] = auth.uid()::text)
WITH CHECK (bucket_id = 'vault' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "storage_vault_owner_delete"
ON storage.objects
FOR DELETE
USING (bucket_id = 'vault' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "storage_vault_admin_all"
ON storage.objects
FOR ALL
USING (bucket_id = 'vault' AND public.current_user_is_admin())
WITH CHECK (bucket_id = 'vault' AND public.current_user_is_admin());

CREATE POLICY "storage_stories_images_public_select"
ON storage.objects
FOR SELECT
USING (bucket_id = 'stories_images');

CREATE POLICY "storage_stories_images_owner_manage"
ON storage.objects
FOR ALL
USING (bucket_id = 'stories_images' AND (storage.foldername(name))[1] = auth.uid()::text)
WITH CHECK (bucket_id = 'stories_images' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "storage_stories_images_admin_manage"
ON storage.objects
FOR ALL
USING (bucket_id = 'stories_images' AND public.current_user_is_admin())
WITH CHECK (bucket_id = 'stories_images' AND public.current_user_is_admin());

CREATE POLICY "storage_user_gallery_public_select"
ON storage.objects
FOR SELECT
USING (bucket_id = 'user-gallery');

CREATE POLICY "storage_user_gallery_owner_manage"
ON storage.objects
FOR ALL
USING (bucket_id = 'user-gallery' AND (storage.foldername(name))[1] = auth.uid()::text)
WITH CHECK (bucket_id = 'user-gallery' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "storage_user_gallery_admin_manage"
ON storage.objects
FOR ALL
USING (bucket_id = 'user-gallery' AND public.current_user_is_admin())
WITH CHECK (bucket_id = 'user-gallery' AND public.current_user_is_admin());


-- FILE: rls/stories-rls.sql
ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.story_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.story_comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "stories_public_select"
ON public.stories
FOR SELECT
USING (is_archived = false OR auth.uid() = uploader_id OR public.current_user_is_admin());

CREATE POLICY "stories_owner_manage"
ON public.stories
FOR ALL
USING (auth.uid() = uploader_id)
WITH CHECK (auth.uid() = uploader_id);

CREATE POLICY "stories_admin_all"
ON public.stories
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());

CREATE POLICY "story_likes_public_select"
ON public.story_likes
FOR SELECT
USING (true);

CREATE POLICY "story_likes_owner_manage"
ON public.story_likes
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "story_likes_admin_all"
ON public.story_likes
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());

CREATE POLICY "story_comments_public_select"
ON public.story_comments
FOR SELECT
USING (true);

CREATE POLICY "story_comments_owner_manage"
ON public.story_comments
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "story_comments_admin_all"
ON public.story_comments
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());


-- FILE: rls/users-rls.sql
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;


CREATE POLICY "profiles_public_select"
ON public.profiles
FOR SELECT
USING (true);

CREATE POLICY "profiles_admin_all"
ON public.profiles
FOR ALL
USING (public.current_user_is_admin())
WITH CHECK (public.current_user_is_admin());


