-- AUTOGENERATED by sql/sql-gen.sh. DO NOT EDIT.

-- Drops the entire public schema. Dangerous.
drop schema if exists public cascade;
create schema public;
grant usage on schema public to anon, authenticated, service_role;
