#!/usr/bin/env bash
# Bash fallback bundler. Mirrors sql/sql-gen.dart in case dart isn't available.

set -euo pipefail
cd "$(dirname "$0")/.."

HEADER="-- AUTOGENERATED by sql/sql-gen.sh. DO NOT EDIT."

concat() {
  local out="$1"; shift
  { echo "$HEADER"; echo; } > "$out"
  for d in "$@"; do
    [ -d "$d" ] || continue
    for f in "$d"/*.sql; do
      [ -f "$f" ] || continue
      echo "-- ==== $f ====" >> "$out"
      cat "$f" >> "$out"
      echo "" >> "$out"
    done
  done
  echo "wrote $out"
}

concat sql/full-schema.sql   sql/schema sql/admin/schema
concat sql/full-views.sql    sql/views  sql/admin/views
concat sql/full-rpc.sql      sql/rpc    sql/admin/rpc
concat sql/full-triggers.sql sql/triggers
concat sql/full-rls.sql      sql/rls    sql/admin/rls

{
  echo "$HEADER"; echo
  echo "-- SCHEMA";   cat sql/full-schema.sql
  echo "-- VIEWS";    cat sql/full-views.sql
  echo "-- RPC";      cat sql/full-rpc.sql
  echo "-- TRIGGERS"; cat sql/full-triggers.sql
  echo "-- RLS";      cat sql/full-rls.sql
} > sql/full-copy-paste.sql
echo "wrote sql/full-copy-paste.sql"

cat > sql/reset.sql <<SQL
$HEADER

-- Drops the entire public schema. Dangerous.
drop schema if exists public cascade;
create schema public;
grant usage on schema public to anon, authenticated, service_role;
SQL
echo "wrote sql/reset.sql"
