/// SQL bundler.
///
/// Concatenates modular SQL under `sql/` into `full-*.sql` files suitable
/// for copy/pasting into the Supabase SQL editor or running with psql.
///
/// Ordering matters because extensions -> enums -> tables -> views -> rpc
/// -> triggers -> rls. Admin-specific SQL is appended after its public
/// counterpart within each phase.
///
/// Usage: `dart run sql/sql-gen.dart`

// ignore_for_file: avoid_print
import 'dart:io';

const String _header =
    '-- AUTOGENERATED by sql/sql-gen.dart. DO NOT EDIT.\n\n';

Future<String> _readAll(List<String> paths) async {
  final buf = StringBuffer(_header);
  for (final p in paths) {
    final f = File(p);
    if (!await f.exists()) continue;
    buf
      ..writeln('-- ==== $p ====')
      ..writeln(await f.readAsString())
      ..writeln();
  }
  return buf.toString();
}

Future<List<String>> _listSorted(Directory dir) async {
  if (!await dir.exists()) return const [];
  final entries =
      await dir.list(recursive: false, followLinks: false).toList();
  final files = entries
      .whereType<File>()
      .where((f) => f.path.endsWith('.sql'))
      .map((f) => f.path)
      .toList()
    ..sort();
  return files;
}

Future<void> _write(String target, String content) async {
  final f = File(target);
  await f.writeAsString(content);
  print('wrote ${f.path}');
}

Future<void> main() async {
  final root = Directory('sql');
  if (!await root.exists()) {
    stderr.writeln('sql/ directory not found; run from repo root.');
    exitCode = 1;
    return;
  }

  final schema = [
    ...await _listSorted(Directory('sql/schema')),
    ...await _listSorted(Directory('sql/admin/schema')),
  ];
  final views = [
    ...await _listSorted(Directory('sql/views')),
    ...await _listSorted(Directory('sql/admin/views')),
  ];
  final rpc = [
    ...await _listSorted(Directory('sql/rpc')),
    ...await _listSorted(Directory('sql/admin/rpc')),
  ];
  final triggers = await _listSorted(Directory('sql/triggers'));
  final rls = [
    ...await _listSorted(Directory('sql/rls')),
    ...await _listSorted(Directory('sql/admin/rls')),
  ];

  final schemaSql = await _readAll(schema);
  final viewsSql = await _readAll(views);
  final rpcSql = await _readAll(rpc);
  final triggersSql = await _readAll(triggers);
  final rlsSql = await _readAll(rls);

  await _write('sql/full-schema.sql', schemaSql);
  await _write('sql/full-views.sql', viewsSql);
  await _write('sql/full-rpc.sql', rpcSql);
  await _write('sql/full-triggers.sql', triggersSql);
  await _write('sql/full-rls.sql', rlsSql);

  final combined = StringBuffer()
    ..write(_header)
    ..writeln('-- SCHEMA')
    ..writeln(schemaSql)
    ..writeln('-- VIEWS')
    ..writeln(viewsSql)
    ..writeln('-- RPC')
    ..writeln(rpcSql)
    ..writeln('-- TRIGGERS')
    ..writeln(triggersSql)
    ..writeln('-- RLS')
    ..writeln(rlsSql);
  await _write('sql/full-copy-paste.sql', combined.toString());

  await _write(
    'sql/reset.sql',
    '$_header-- Drops the entire public schema. Dangerous.\n'
    'drop schema if exists public cascade;\n'
    'create schema public;\n'
    'grant usage on schema public to anon, authenticated, service_role;\n',
  );
}
